// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kontra/v1/actor_service.proto

package kontrav1

import (
	_ "github.com/cludden/protoc-gen-go-temporal/gen/temporal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_kontra_v1_actor_service_proto protoreflect.FileDescriptor

const file_kontra_v1_actor_service_proto_rawDesc = "" +
	"\n" +
	"\x1dkontra/v1/actor_service.proto\x12\tkontra.v1\x1a\x1atemporal/v1/temporal.proto\x1a\x15kontra/v1/entry.proto2\xa4\x01\n" +
	"\fActorService\x12n\n" +
	"\x03Run\x12\x15.kontra.v1.EntryInput\x1a\x12.kontra.v1.BareRef\"<\x8a\xc4\x038*.actor-${!idempotency_key.or(run_id).or(\"run\")}\xc2\x01\x05\x12\x03run\x1a$\x8a\xc4\x03 \n" +
	"\fkontra-actor\"\x10\b\x01\x12\fkontra.actorBAZ?github.com/medmahmoudi26/kontra/handler/_gen/kontra/v1;kontrav1b\x06proto3"

var file_kontra_v1_actor_service_proto_goTypes = []any{
	(*EntryInput)(nil), // 0: kontra.v1.EntryInput
	(*BareRef)(nil),    // 1: kontra.v1.BareRef
}
var file_kontra_v1_actor_service_proto_depIdxs = []int32{
	0, // 0: kontra.v1.ActorService.Run:input_type -> kontra.v1.EntryInput
	1, // 1: kontra.v1.ActorService.Run:output_type -> kontra.v1.BareRef
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kontra_v1_actor_service_proto_init() }
func file_kontra_v1_actor_service_proto_init() {
	if File_kontra_v1_actor_service_proto != nil {
		return
	}
	file_kontra_v1_entry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kontra_v1_actor_service_proto_rawDesc), len(file_kontra_v1_actor_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kontra_v1_actor_service_proto_goTypes,
		DependencyIndexes: file_kontra_v1_actor_service_proto_depIdxs,
	}.Build()
	File_kontra_v1_actor_service_proto = out.File
	file_kontra_v1_actor_service_proto_goTypes = nil
	file_kontra_v1_actor_service_proto_depIdxs = nil
}
