// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kontra/v1/actor.proto

package kontrav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Input to an actor over ONE batch — the single argument to the ActorWorkflow.
type ActorRunInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This batch's units, inline (the CLI/DIY path). Exactly one of units / units_ref
	// carries the batch.
	Units []*structpb.Value `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	// OR the batch as a CAS ref the actor materializes (refs-as-currency, ADR 0007).
	UnitsRef *BareRef `protobuf:"bytes,2,opt,name=units_ref,json=unitsRef,proto3" json:"units_ref,omitempty"`
	// Run-wide config -> the author's self.params. NON-secret (params ride history).
	Params *structpb.Struct `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	// Lineage the dispatcher stamps (ADR 0006); surfaced to the author as self.run_id /
	// self.idempotency_key. tenant is dispatcher bookkeeping. "" = unset (CLI/DIY path).
	RunId          string `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Tenant         string `protobuf:"bytes,5,opt,name=tenant,proto3" json:"tenant,omitempty"`
	IdempotencyKey string `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Content-pinned identity (ADR 0011): the OCI image digest this run was designed
	// against. The worker self-verifies its running digest and fails fast (non-retryable,
	// ActorDigestDrift) on drift. "" = unpinned (enforcement off).
	ExpectedDigest string `protobuf:"bytes,7,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	// When true the actor returns a BareRef (result_ref) instead of inline results, so the
	// dispatcher stays ref-only.
	ReturnRef     bool `protobuf:"varint,8,opt,name=return_ref,json=returnRef,proto3" json:"return_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorRunInput) Reset() {
	*x = ActorRunInput{}
	mi := &file_kontra_v1_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorRunInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRunInput) ProtoMessage() {}

func (x *ActorRunInput) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRunInput.ProtoReflect.Descriptor instead.
func (*ActorRunInput) Descriptor() ([]byte, []int) {
	return file_kontra_v1_actor_proto_rawDescGZIP(), []int{0}
}

func (x *ActorRunInput) GetUnits() []*structpb.Value {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *ActorRunInput) GetUnitsRef() *BareRef {
	if x != nil {
		return x.UnitsRef
	}
	return nil
}

func (x *ActorRunInput) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ActorRunInput) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ActorRunInput) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ActorRunInput) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ActorRunInput) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *ActorRunInput) GetReturnRef() bool {
	if x != nil {
		return x.ReturnRef
	}
	return false
}

// The result of running an actor over one batch: the {results, failures} envelope, inline
// or as a CAS ref. Formalizes the envelope that today lives only in each SDK (Python
// dataclass / TS type / Go struct), never in proto.
type ActorRunResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The arun's output units. Empty when result_ref is set.
	Results []*structpb.Value `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Per-unit failures isolated within this run (the durability surface).
	Failures []*PerUnitFailure `protobuf:"bytes,2,rep,name=failures,proto3" json:"failures,omitempty"`
	// Set when ActorRunInput.return_ref: the {results, failures} envelope content-addressed.
	ResultRef     *BareRef `protobuf:"bytes,3,opt,name=result_ref,json=resultRef,proto3" json:"result_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorRunResult) Reset() {
	*x = ActorRunResult{}
	mi := &file_kontra_v1_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRunResult) ProtoMessage() {}

func (x *ActorRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRunResult.ProtoReflect.Descriptor instead.
func (*ActorRunResult) Descriptor() ([]byte, []int) {
	return file_kontra_v1_actor_proto_rawDescGZIP(), []int{1}
}

func (x *ActorRunResult) GetResults() []*structpb.Value {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ActorRunResult) GetFailures() []*PerUnitFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

func (x *ActorRunResult) GetResultRef() *BareRef {
	if x != nil {
		return x.ResultRef
	}
	return nil
}

// One isolated unit failure. The full unit is the correlation key (no positional index).
type PerUnitFailure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Unit  *structpb.Value        `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Error *ErrorInfo             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// "terminal"  — non-retryable: isolated on the first attempt (author NonRetryable, a
	//
	//	non_retryable_errors match, or ActorDigestDrift/SessionUnrecoverable).
	//
	// "exhausted" — retryable: isolated after the activity's retry policy ran out.
	Category      string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerUnitFailure) Reset() {
	*x = PerUnitFailure{}
	mi := &file_kontra_v1_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerUnitFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerUnitFailure) ProtoMessage() {}

func (x *PerUnitFailure) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerUnitFailure.ProtoReflect.Descriptor instead.
func (*PerUnitFailure) Descriptor() ([]byte, []int) {
	return file_kontra_v1_actor_proto_rawDescGZIP(), []int{2}
}

func (x *PerUnitFailure) GetUnit() *structpb.Value {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *PerUnitFailure) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *PerUnitFailure) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cross-language error-type name (e.g. SessionLost, ActorDigestDrift, the author's
	// NonRetryable subclass name) — matched against the activity's non-retryable error types.
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_kontra_v1_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_kontra_v1_actor_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kontra_v1_actor_proto protoreflect.FileDescriptor

const file_kontra_v1_actor_proto_rawDesc = "" +
	"\n" +
	"\x15kontra/v1/actor.proto\x12\tkontra.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15kontra/v1/entry.proto\"\xbf\x02\n" +
	"\rActorRunInput\x12,\n" +
	"\x05units\x18\x01 \x03(\v2\x16.google.protobuf.ValueR\x05units\x12/\n" +
	"\tunits_ref\x18\x02 \x01(\v2\x12.kontra.v1.BareRefR\bunitsRef\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x16\n" +
	"\x06tenant\x18\x05 \x01(\tR\x06tenant\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x0fexpected_digest\x18\a \x01(\tR\x0eexpectedDigest\x12\x1d\n" +
	"\n" +
	"return_ref\x18\b \x01(\bR\treturnRef\"\xac\x01\n" +
	"\x0eActorRunResult\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.google.protobuf.ValueR\aresults\x125\n" +
	"\bfailures\x18\x02 \x03(\v2\x19.kontra.v1.PerUnitFailureR\bfailures\x121\n" +
	"\n" +
	"result_ref\x18\x03 \x01(\v2\x12.kontra.v1.BareRefR\tresultRef\"\x84\x01\n" +
	"\x0ePerUnitFailure\x12*\n" +
	"\x04unit\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x04unit\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x14.kontra.v1.ErrorInfoR\x05error\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"9\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageBGZEgithub.com/medmahmoudi26/kontra-local/handler/_gen/kontra/v1;kontrav1b\x06proto3"

var (
	file_kontra_v1_actor_proto_rawDescOnce sync.Once
	file_kontra_v1_actor_proto_rawDescData []byte
)

func file_kontra_v1_actor_proto_rawDescGZIP() []byte {
	file_kontra_v1_actor_proto_rawDescOnce.Do(func() {
		file_kontra_v1_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kontra_v1_actor_proto_rawDesc), len(file_kontra_v1_actor_proto_rawDesc)))
	})
	return file_kontra_v1_actor_proto_rawDescData
}

var file_kontra_v1_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kontra_v1_actor_proto_goTypes = []any{
	(*ActorRunInput)(nil),   // 0: kontra.v1.ActorRunInput
	(*ActorRunResult)(nil),  // 1: kontra.v1.ActorRunResult
	(*PerUnitFailure)(nil),  // 2: kontra.v1.PerUnitFailure
	(*ErrorInfo)(nil),       // 3: kontra.v1.ErrorInfo
	(*structpb.Value)(nil),  // 4: google.protobuf.Value
	(*BareRef)(nil),         // 5: kontra.v1.BareRef
	(*structpb.Struct)(nil), // 6: google.protobuf.Struct
}
var file_kontra_v1_actor_proto_depIdxs = []int32{
	4, // 0: kontra.v1.ActorRunInput.units:type_name -> google.protobuf.Value
	5, // 1: kontra.v1.ActorRunInput.units_ref:type_name -> kontra.v1.BareRef
	6, // 2: kontra.v1.ActorRunInput.params:type_name -> google.protobuf.Struct
	4, // 3: kontra.v1.ActorRunResult.results:type_name -> google.protobuf.Value
	2, // 4: kontra.v1.ActorRunResult.failures:type_name -> kontra.v1.PerUnitFailure
	5, // 5: kontra.v1.ActorRunResult.result_ref:type_name -> kontra.v1.BareRef
	4, // 6: kontra.v1.PerUnitFailure.unit:type_name -> google.protobuf.Value
	3, // 7: kontra.v1.PerUnitFailure.error:type_name -> kontra.v1.ErrorInfo
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_kontra_v1_actor_proto_init() }
func file_kontra_v1_actor_proto_init() {
	if File_kontra_v1_actor_proto != nil {
		return
	}
	file_kontra_v1_entry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kontra_v1_actor_proto_rawDesc), len(file_kontra_v1_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kontra_v1_actor_proto_goTypes,
		DependencyIndexes: file_kontra_v1_actor_proto_depIdxs,
		MessageInfos:      file_kontra_v1_actor_proto_msgTypes,
	}.Build()
	File_kontra_v1_actor_proto = out.File
	file_kontra_v1_actor_proto_goTypes = nil
	file_kontra_v1_actor_proto_depIdxs = nil
}
