// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kontra/v1/entry.proto

package kontrav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A bare claim-check ref: {sha256, size, meta}. The content-addressed shape the
// codec/blob layer trades in. Shared by the TS BareRef / ClaimCheckRef /
// NodeResultRef.claimcheck arm and the handler's blob activities — kontra.store_blob
// returns it, kontra.fetch_blob accepts it (handler/activity.go), and a Python caller
// dereferences a result through the same pair.
type BareRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                                                          // byte length of json.dumps(units)
	Meta          map[string]string      `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // codec provenance; {} today
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BareRef) Reset() {
	*x = BareRef{}
	mi := &file_kontra_v1_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BareRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BareRef) ProtoMessage() {}

func (x *BareRef) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BareRef.ProtoReflect.Descriptor instead.
func (*BareRef) Descriptor() ([]byte, []int) {
	return file_kontra_v1_entry_proto_rawDescGZIP(), []int{0}
}

func (x *BareRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BareRef) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BareRef) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Input to the kontra.actor:run operation — the ONE input type the orchestrator and
// both SDKs serialize. The TS interpreter sets exactly these fields, and the Python
// TypedDict is exactly this set (a field-congruence test asserts it). The actor runs
// ONE batch per call (ADR 0012, ADR 0023 §2): the caller splits a large input into
// multiple calls, so no sharding knob rides here — `session_id` names the scope a call
// belongs to, it does not divide one.
type EntryInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The whole ActorInput batch, inline (the CLI path) — arbitrary JSON values,
	// hence Value. Exactly one of `units` / `input_ref` carries the batch.
	Units []*structpb.Value `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	// The batch as a CAS ref the Python fetch_blob materializes (refs-as-currency).
	InputRef *BareRef `protobuf:"bytes,2,opt,name=input_ref,json=inputRef,proto3" json:"input_ref,omitempty"`
	// When true the actor returns a BareRef instead of a raw list, so the
	// interpreter stays ref-only.
	ReturnRef bool `protobuf:"varint,6,opt,name=return_ref,json=returnRef,proto3" json:"return_ref,omitempty"`
	// Run lineage the orchestrator stamps onto every node's child run (all empty on the
	// CLI/back-compat path). `run_id` + `idempotency_key` are surfaced to the author as
	// `self.run_id` / `self.idempotency_key`. Plain strings — "" means unset.
	RunId          string `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	IdempotencyKey string `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Which graph node this actor run serves (mirrors run.proto's node_id lineage). The
	// Nexus dispatch path folds it into the backing workflow id (`act-{name}-{run_id}-{node_id}`)
	// so two nodes of the SAME actor in one graph get distinct, deterministic runs. "" on the
	// DIY/CLI path (single actor, no graph).
	NodeId string `protobuf:"bytes,12,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Content-pinned actor identity (ADR 0011): the OCI image digest this node was
	// designed against, stamped by the orchestrator from the catalog. The worker
	// serving (name, version) self-verifies its own running digest against this at
	// session start and fails fast (non-retryable) on drift. "" = unpinned (CLI/dev path).
	ExpectedDigest string `protobuf:"bytes,10,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	// Run-wide config the caller sets, reaching the author as `self.params` — and what any
	// param-bound knob the author declares resolves against. Arbitrary JSON object; {} = none.
	Params *structpb.Struct `protobuf:"bytes,11,opt,name=params,proto3" json:"params,omitempty"`
	// Which Method of the actor this dispatch calls (ADR 0023 §5). An actor declares as many
	// Methods as it has jobs and the caller names one; the callee resolves the name per batch,
	// which is what lets ONE loaded session serve several. "" = unnamed, which an actor with a
	// single Method accepts and an actor with several refuses rather than taking declaration
	// order.
	Method string `protobuf:"bytes,13,opt,name=method,proto3" json:"method,omitempty"`
	// Which Session this dispatch belongs to (ADR 0023 §4, §6). A caller opens a Session, calls
	// its Methods, and closes it; the id is what binds those calls to the ONE activated actor,
	// so it rides EVERY dispatch inside the scope and not only the one that opened it. "" = no
	// scope was opened, the pre-v2 path where each dispatch stands alone.
	SessionId     string `protobuf:"bytes,14,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryInput) Reset() {
	*x = EntryInput{}
	mi := &file_kontra_v1_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryInput) ProtoMessage() {}

func (x *EntryInput) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryInput.ProtoReflect.Descriptor instead.
func (*EntryInput) Descriptor() ([]byte, []int) {
	return file_kontra_v1_entry_proto_rawDescGZIP(), []int{1}
}

func (x *EntryInput) GetUnits() []*structpb.Value {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *EntryInput) GetInputRef() *BareRef {
	if x != nil {
		return x.InputRef
	}
	return nil
}

func (x *EntryInput) GetReturnRef() bool {
	if x != nil {
		return x.ReturnRef
	}
	return false
}

func (x *EntryInput) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *EntryInput) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EntryInput) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EntryInput) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *EntryInput) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *EntryInput) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EntryInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_kontra_v1_entry_proto protoreflect.FileDescriptor

const file_kontra_v1_entry_proto_rawDesc = "" +
	"\n" +
	"\x15kontra/v1/entry.proto\x12\tkontra.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa0\x01\n" +
	"\aBareRef\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x120\n" +
	"\x04meta\x18\x03 \x03(\v2\x1c.kontra.v1.BareRef.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x03\n" +
	"\n" +
	"EntryInput\x12,\n" +
	"\x05units\x18\x01 \x03(\v2\x16.google.protobuf.ValueR\x05units\x12/\n" +
	"\tinput_ref\x18\x02 \x01(\v2\x12.kontra.v1.BareRefR\binputRef\x12\x1d\n" +
	"\n" +
	"return_ref\x18\x06 \x01(\bR\treturnRef\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12\x17\n" +
	"\anode_id\x18\f \x01(\tR\x06nodeId\x12'\n" +
	"\x0fexpected_digest\x18\n" +
	" \x01(\tR\x0eexpectedDigest\x12/\n" +
	"\x06params\x18\v \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x16\n" +
	"\x06method\x18\r \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"session_id\x18\x0e \x01(\tR\tsessionIdJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\b\x10\tR\n" +
	"output_uriR\x11parallel_sessionsR\n" +
	"chunk_sizeR\x06tenantBAZ?github.com/medmahmoudi26/kontra/handler/_gen/kontra/v1;kontrav1b\x06proto3"

var (
	file_kontra_v1_entry_proto_rawDescOnce sync.Once
	file_kontra_v1_entry_proto_rawDescData []byte
)

func file_kontra_v1_entry_proto_rawDescGZIP() []byte {
	file_kontra_v1_entry_proto_rawDescOnce.Do(func() {
		file_kontra_v1_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kontra_v1_entry_proto_rawDesc), len(file_kontra_v1_entry_proto_rawDesc)))
	})
	return file_kontra_v1_entry_proto_rawDescData
}

var file_kontra_v1_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kontra_v1_entry_proto_goTypes = []any{
	(*BareRef)(nil),         // 0: kontra.v1.BareRef
	(*EntryInput)(nil),      // 1: kontra.v1.EntryInput
	nil,                     // 2: kontra.v1.BareRef.MetaEntry
	(*structpb.Value)(nil),  // 3: google.protobuf.Value
	(*structpb.Struct)(nil), // 4: google.protobuf.Struct
}
var file_kontra_v1_entry_proto_depIdxs = []int32{
	2, // 0: kontra.v1.BareRef.meta:type_name -> kontra.v1.BareRef.MetaEntry
	3, // 1: kontra.v1.EntryInput.units:type_name -> google.protobuf.Value
	0, // 2: kontra.v1.EntryInput.input_ref:type_name -> kontra.v1.BareRef
	4, // 3: kontra.v1.EntryInput.params:type_name -> google.protobuf.Struct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kontra_v1_entry_proto_init() }
func file_kontra_v1_entry_proto_init() {
	if File_kontra_v1_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kontra_v1_entry_proto_rawDesc), len(file_kontra_v1_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kontra_v1_entry_proto_goTypes,
		DependencyIndexes: file_kontra_v1_entry_proto_depIdxs,
		MessageInfos:      file_kontra_v1_entry_proto_msgTypes,
	}.Build()
	File_kontra_v1_entry_proto = out.File
	file_kontra_v1_entry_proto_goTypes = nil
	file_kontra_v1_entry_proto_depIdxs = nil
}
