// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kontra/v1/run.proto

package kontrav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity / routing. version is IMMUTABLE — a schema change MUST bump it, and
	// build refuses to overwrite an existing (name, version) (ADR 0004, content-
	// pinned identity). Resolves the {name}-{version} queue / Nexus endpoint.
	Actor *Actor `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	// Lineage. run_id is SERVER-MINTED, immutable, and UNIQUE PER EXECUTION — minted
	// at POST /api/runs, never accepted from the client, and distinct from the user-
	// facing graph label (ADR 0006). It is the lineage key threaded into child
	// workflow ids, codec provenance, and the future Iceberg partition columns.
	RunId  string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId string `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // which graph node produced this dispatch
	// Tenancy. Selects the Temporal namespace (namespace-per-author in prod) and
	// scopes the CAS key. Tenant-free today (cas/<sha[:2]>/<sha>); becomes
	// cas/{tenant}/<sha[:2]>/<sha> under namespace-per-author. Present NOW as
	// "default" so adding real tenants later needs no history migration (ADR 0001).
	Tenant string `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Idempotency. A stable (run_id, node_id, generation, unit-index) tuple the SDK
	// exposes to the author as self.idempotency_key, so at-least-once retries and the
	// Iceberg append dedup instead of double-firing side effects.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// The batch payload: OPAQUE. JSON-encoded units, or a claim-check ref the codec
	// rehydrates transparently. The proto never sees per-actor shape.
	Payload []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Run-wide config (the params block), JSON-encoded, validated against the params
	// JSON Schema. NON-SECRET only — secrets travel as a {secret_ref} resolved out of
	// band at load time, never inline (params ride Temporal history in plaintext
	// today; this is the split the review flagged).
	Params []byte `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	// Dispatch knobs — the dispatcher's concern, not a workflow constant.
	Dispatch      *DispatchOptions `protobuf:"bytes,8,opt,name=dispatch,proto3" json:"dispatch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEnvelope) Reset() {
	*x = RunEnvelope{}
	mi := &file_kontra_v1_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEnvelope) ProtoMessage() {}

func (x *RunEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEnvelope.ProtoReflect.Descriptor instead.
func (*RunEnvelope) Descriptor() ([]byte, []int) {
	return file_kontra_v1_run_proto_rawDescGZIP(), []int{0}
}

func (x *RunEnvelope) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *RunEnvelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEnvelope) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RunEnvelope) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RunEnvelope) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RunEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunEnvelope) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RunEnvelope) GetDispatch() *DispatchOptions {
	if x != nil {
		return x.Dispatch
	}
	return nil
}

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // immutable; bump on any input/output/params schema change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_kontra_v1_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_kontra_v1_run_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Actor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DispatchOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChunkSize         uint32                 `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`                             // units per chunk (one chunk == one session)
	ParallelSessions  uint32                 `protobuf:"varint,2,opt,name=parallel_sessions,json=parallelSessions,proto3" json:"parallel_sessions,omitempty"`        // max concurrent sessions
	ScheduleToCloseMs uint64                 `protobuf:"varint,3,opt,name=schedule_to_close_ms,json=scheduleToCloseMs,proto3" json:"schedule_to_close_ms,omitempty"` // the Nexus operation deadline (caller-set; must
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DispatchOptions) Reset() {
	*x = DispatchOptions{}
	mi := &file_kontra_v1_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchOptions) ProtoMessage() {}

func (x *DispatchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchOptions.ProtoReflect.Descriptor instead.
func (*DispatchOptions) Descriptor() ([]byte, []int) {
	return file_kontra_v1_run_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchOptions) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *DispatchOptions) GetParallelSessions() uint32 {
	if x != nil {
		return x.ParallelSessions
	}
	return 0
}

func (x *DispatchOptions) GetScheduleToCloseMs() uint64 {
	if x != nil {
		return x.ScheduleToCloseMs
	}
	return 0
}

var File_kontra_v1_run_proto protoreflect.FileDescriptor

const file_kontra_v1_run_proto_rawDesc = "" +
	"\n" +
	"\x13kontra/v1/run.proto\x12\tkontra.v1\"\x90\x02\n" +
	"\vRunEnvelope\x12&\n" +
	"\x05actor\x18\x01 \x01(\v2\x10.kontra.v1.ActorR\x05actor\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x16\n" +
	"\x06params\x18\a \x01(\fR\x06params\x126\n" +
	"\bdispatch\x18\b \x01(\v2\x1a.kontra.v1.DispatchOptionsR\bdispatch\"5\n" +
	"\x05Actor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x8e\x01\n" +
	"\x0fDispatchOptions\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x01 \x01(\rR\tchunkSize\x12+\n" +
	"\x11parallel_sessions\x18\x02 \x01(\rR\x10parallelSessions\x12/\n" +
	"\x14schedule_to_close_ms\x18\x03 \x01(\x04R\x11scheduleToCloseMsBGZEgithub.com/medmahmoudi26/kontra-local/handler/_gen/kontra/v1;kontrav1b\x06proto3"

var (
	file_kontra_v1_run_proto_rawDescOnce sync.Once
	file_kontra_v1_run_proto_rawDescData []byte
)

func file_kontra_v1_run_proto_rawDescGZIP() []byte {
	file_kontra_v1_run_proto_rawDescOnce.Do(func() {
		file_kontra_v1_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kontra_v1_run_proto_rawDesc), len(file_kontra_v1_run_proto_rawDesc)))
	})
	return file_kontra_v1_run_proto_rawDescData
}

var file_kontra_v1_run_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kontra_v1_run_proto_goTypes = []any{
	(*RunEnvelope)(nil),     // 0: kontra.v1.RunEnvelope
	(*Actor)(nil),           // 1: kontra.v1.Actor
	(*DispatchOptions)(nil), // 2: kontra.v1.DispatchOptions
}
var file_kontra_v1_run_proto_depIdxs = []int32{
	1, // 0: kontra.v1.RunEnvelope.actor:type_name -> kontra.v1.Actor
	2, // 1: kontra.v1.RunEnvelope.dispatch:type_name -> kontra.v1.DispatchOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kontra_v1_run_proto_init() }
func file_kontra_v1_run_proto_init() {
	if File_kontra_v1_run_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kontra_v1_run_proto_rawDesc), len(file_kontra_v1_run_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kontra_v1_run_proto_goTypes,
		DependencyIndexes: file_kontra_v1_run_proto_depIdxs,
		MessageInfos:      file_kontra_v1_run_proto_msgTypes,
	}.Build()
	File_kontra_v1_run_proto = out.File
	file_kontra_v1_run_proto_goTypes = nil
	file_kontra_v1_run_proto_depIdxs = nil
}
