// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: kontra/v1/actor_service.proto

/* eslint-disable */
import { type BareRef, type EntryInput } from "./entry";

export const protobufPackage = "kontra.v1";

/**
 * The canonical dispatch contract as a Temporal **Nexus** service. Dispatching an actor
 * over one batch IS a Nexus workflow-run operation (`kontra.actor:run`) — the ONE op the
 * TS orchestrator already calls (backend/src/workflows/nexusService.ts). Its typed
 * client + worker + Nexus wiring are generated by protoc-gen-go-temporal from this file;
 * the backing "run" workflow is hand-written in the Go Nexus handler (it schedules the batch
 * as a RunBatch activity on the actor's own task queue and returns a claim-check BareRef).
 *
 * Wire stays JSON (ADR 0002): EntryInput/BareRef are reused verbatim from entry.proto, so
 * the orchestrator dispatches unchanged. The service/op names below MUST match the frozen
 * cross-language contract (identity.go / nexusService.ts): service "kontra.actor", op "run".
 */
export interface ActorService {
  /** kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path). */
  Run(request: EntryInput): Promise<BareRef>;
}
