// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: kontra/v1/entry.proto

/* eslint-disable */

export const protobufPackage = "kontra.v1";

/**
 * A bare claim-check ref: {sha256, size, meta}. The content-addressed shape the
 * codec/blob layer trades in. Shared by the TS BareRef / ClaimCheckRef /
 * NodeResultRef.claimcheck arm and the handler's blob activities — kontra.store_blob
 * returns it, kontra.fetch_blob accepts it (handler/activity.go), and a Python caller
 * dereferences a result through the same pair.
 */
export interface BareRef {
  sha256: string;
  /** byte length of json.dumps(units) */
  size: number;
  /** codec provenance; {} today */
  meta: { [key: string]: string };
}

export interface BareRef_MetaEntry {
  key: string;
  value: string;
}

/**
 * Input to the kontra.actor:run operation — the ONE input type the orchestrator and
 * both SDKs serialize. The TS interpreter sets exactly these fields, and the Python
 * TypedDict is exactly this set (a field-congruence test asserts it). The actor runs
 * ONE batch per call (ADR 0012, ADR 0023 §2): the caller splits a large input into
 * multiple calls, so no sharding knob rides here — `session_id` names the scope a call
 * belongs to, it does not divide one.
 */
export interface EntryInput {
  /**
   * The whole ActorInput batch, inline (the CLI path) — arbitrary JSON values,
   * hence Value. Exactly one of `units` / `input_ref` carries the batch.
   */
  units: any[];
  /** The batch as a CAS ref the Python fetch_blob materializes (refs-as-currency). */
  input_ref:
    | BareRef
    | undefined;
  /**
   * When true the actor returns a BareRef instead of a raw list, so the
   * interpreter stays ref-only.
   */
  return_ref: boolean;
  /**
   * Run lineage the orchestrator stamps onto every node's child run (all empty on the
   * CLI/back-compat path). `run_id` + `idempotency_key` are surfaced to the author as
   * `self.run_id` / `self.idempotency_key`. Plain strings — "" means unset.
   */
  run_id: string;
  idempotency_key: string;
  /**
   * Which graph node this actor run serves (mirrors run.proto's node_id lineage). The
   * Nexus dispatch path folds it into the backing workflow id (`act-{name}-{run_id}-{node_id}`)
   * so two nodes of the SAME actor in one graph get distinct, deterministic runs. "" on the
   * DIY/CLI path (single actor, no graph).
   */
  node_id: string;
  /**
   * Content-pinned actor identity (ADR 0011): the OCI image digest this node was
   * designed against, stamped by the orchestrator from the catalog. The worker
   * serving (name, version) self-verifies its own running digest against this at
   * session start and fails fast (non-retryable) on drift. "" = unpinned (CLI/dev path).
   */
  expected_digest: string;
  /**
   * Run-wide config the caller sets, reaching the author as `self.params` — and what any
   * param-bound knob the author declares resolves against. Arbitrary JSON object; {} = none.
   */
  params:
    | { [key: string]: any }
    | undefined;
  /**
   * Which Method of the actor this dispatch calls (ADR 0023 §5). An actor declares as many
   * Methods as it has jobs and the caller names one; the callee resolves the name per batch,
   * which is what lets ONE loaded session serve several. "" = unnamed, which an actor with a
   * single Method accepts and an actor with several refuses rather than taking declaration
   * order.
   */
  method: string;
  /**
   * Which Session this dispatch belongs to (ADR 0023 §4, §6). A caller opens a Session, calls
   * its Methods, and closes it; the id is what binds those calls to the ONE activated actor,
   * so it rides EVERY dispatch inside the scope and not only the one that opened it. "" = no
   * scope was opened, the pre-v2 path where each dispatch stands alone.
   */
  session_id: string;
}
