// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: temporal/v1/temporal.proto

/* eslint-disable */
import { type Duration } from "../../google/protobuf/duration";
import { type Priority } from "../api/common/v1/message";
import { type VersioningBehavior, type WorkflowIdConflictPolicy } from "../api/enums/v1/workflow";

export const protobufPackage = "temporal.v1";

/**
 * IDReusePolicy defines how new runs of a workflow with a particular ID may or
 * may not be allowed. Note that it is *never* valid to have two actively
 * running instances of the same workflow id.
 */
export enum IDReusePolicy {
  WORKFLOW_ID_REUSE_POLICY_UNSPECIFIED = 0,
  /** WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE - Allow starting a workflow execution using the same workflow id. */
  WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE = 1,
  /**
   * WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY - Allow starting a workflow execution using the same workflow id, only when the last
   * execution's final state is one of [terminated, cancelled, timed out, failed].
   */
  WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY = 2,
  /**
   * WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE - Do not permit re-use of the workflow id for this workflow. Future start workflow requests
   * could potentially change the policy, allowing re-use of the workflow id.
   */
  WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE = 3,
  /**
   * WORKFLOW_ID_REUSE_POLICY_TERMINATE_IF_RUNNING - If a workflow is running using the same workflow ID, terminate it and start a new one.
   * If no running workflow, then the behavior is the same as ALLOW_DUPLICATE
   */
  WORKFLOW_ID_REUSE_POLICY_TERMINATE_IF_RUNNING = 4,
  UNRECOGNIZED = -1,
}

/** Defines how child workflows will react to their parent completing */
export enum ParentClosePolicy {
  PARENT_CLOSE_POLICY_UNSPECIFIED = 0,
  /** PARENT_CLOSE_POLICY_TERMINATE - The child workflow will also terminate */
  PARENT_CLOSE_POLICY_TERMINATE = 1,
  /** PARENT_CLOSE_POLICY_ABANDON - The child workflow will do nothing */
  PARENT_CLOSE_POLICY_ABANDON = 2,
  /** PARENT_CLOSE_POLICY_REQUEST_CANCEL - Cancellation will be requested of the child workflow */
  PARENT_CLOSE_POLICY_REQUEST_CANCEL = 3,
  UNRECOGNIZED = -1,
}

/**
 * WaitPolicy used to indicate to the server how long the client wishes to wait for a return
 * value from an UpdateWorkflow RPC
 */
export enum WaitPolicy {
  WAIT_POLICY_UNSPECIFIED = 0,
  WAIT_POLICY_ADMITTED = 1,
  WAIT_POLICY_ACCEPTED = 2,
  WAIT_POLICY_COMPLETED = 3,
  UNRECOGNIZED = -1,
}

/**
 * ActivityOptions identifies an rpc method as a Temporal activity definition, and describes
 * available activity configuration options
 */
export interface ActivityOptions {
  /** Fully-qualified activity name */
  name: string;
  /** Override default task queue for activity */
  task_queue: string;
  /** Total time that a workflow is willing to wait for Activity to complete */
  schedule_to_close_timeout:
    | Duration
    | undefined;
  /**
   * Time that the Activity Task can stay in the Task Queue before it is picked up by
   * a Worker
   */
  schedule_to_start_timeout:
    | Duration
    | undefined;
  /** Maximum time of a single Activity execution attempt */
  start_to_close_timeout:
    | Duration
    | undefined;
  /** Heartbeat interval. Activity must call Activity.RecordHeartbeat(ctx, "my-heartbeat") */
  heartbeat_timeout:
    | Duration
    | undefined;
  /**
   * WaitForCancellation - Whether to wait for canceled activity to be completed
   * (activity can be failed, completed, cancel accepted)
   */
  wait_for_cancellation: boolean;
  /**
   * Specifies distribution of work within a task queue
   * using Task Queue Priority and Task Queue Fairness
   */
  priority:
    | Priority
    | undefined;
  /** Specifies how to retry an Activity if an error occurs */
  retry_policy: RetryPolicy | undefined;
}

export interface CLIOptions {
  ignore: boolean;
  name: string;
  usage: string;
  aliases: string[];
}

export interface CLICommandOptions {
  ignore: boolean;
  name: string;
  usage: string;
  aliases: string[];
}

export interface CLIFlagOptions {
  name: string;
  usage: string;
  aliases: string[];
}

export interface CommandOptions {
  ignore: boolean;
}

export interface FieldOptions {
  cli: CLIFlagOptions | undefined;
}

export interface NexusOperationOptions {
  /** boolean flag to disable nexus operation generation for parent */
  disabled: boolean;
  /** fully-qualified nexus operation name */
  name: string;
}

export interface NexusServiceOptions {
  enabled: boolean;
  /** fully-qualified nexus operation name */
  name: string;
}

/**
 * Patch describes how a nondeterministic fix/feature introduced to generated
 * code is implemented. By default, all patches are introduced in PVM_ENABLED
 * mode. Once rollout of updated code has been completed and old workflows have
 * closed and retention window passed (or certain that replay is no longer a risk),
 * the prior code can be removed by switching to PVM_MARKER or removed entirely
 * with PVM_REMOVED. Patch code can also be disabled explicitly using PVM_DISABLED.
 */
export interface Patch {
  version: Patch_Version;
  mode: Patch_Mode;
}

/** enumerates all defined patch versions */
export enum Patch_Version {
  PV_UNSPECIFIED = 0,
  /**
   * PV_64 - wraps expression evaluation in local activities within workflow contexts
   * details: https://cludden.github.io/protoc-gen-go-temporal/docs/guides/fix-versions#fix_version_64_expression_evaluation_local_activity
   */
  PV_64 = 1,
  UNRECOGNIZED = -1,
}

/** enumerates all supported patch configurations */
export enum Patch_Mode {
  /** PVM_ENABLED - both patch and prior code present behind workflow versioning */
  PVM_ENABLED = 0,
  /** PVM_MARKER - only patch code present, workflow version marker present */
  PVM_MARKER = 1,
  /** PVM_REMOVED - only patch code present, workflow version marker removed */
  PVM_REMOVED = 2,
  /** PVM_DISABLED - only prior code present, no patch code or workflow version marker introduced */
  PVM_DISABLED = 3,
  UNRECOGNIZED = -1,
}

/**
 * QueryOptions identifies an rpc method as a Temporal query definition, and describes
 * available query configuration options
 */
export interface QueryOptions {
  /** cli command overrides */
  cli:
    | CLICommandOptions
    | undefined;
  /** Fully-qualified query name */
  name: string;
  /** XNS can be used to configure default activity options for xns workflow executions */
  xns:
    | XNSActivityOptions
    | undefined;
  /** Configure patches, by default, patches are introduced in enabled mode */
  patches: Patch[];
}

/** RetryPolicy describes configuration for activity or child workflow retries */
export interface RetryPolicy {
  initial_interval: Duration | undefined;
  backoff_coefficient: number;
  max_interval: Duration | undefined;
  max_attempts: number;
  non_retryable_error_types: string[];
}

/**
 * ServiceOptions provides options that can be used to define common configuration
 * shared by all methods
 */
export interface ServiceOptions {
  /** Configure patches, by default, patches are introduced in enabled mode */
  patches: Patch[];
  /**
   * Default namespace for child workflows, activities
   *
   * @deprecated
   */
  namespace: string;
  /** Nexus service options */
  nexus:
    | NexusServiceOptions
    | undefined;
  /** Default task queue for all workflows, activities */
  task_queue: string;
}

/**
 * SignalOptions identifies an rpc method as a Temporal singal definition, and describes
 * available signal configuration options
 */
export interface SignalOptions {
  /** cli command overrides */
  cli:
    | CLICommandOptions
    | undefined;
  /** Fully-qualified signal name */
  name: string;
  /** XNS can be used to configure default activity options for xns workflow executions */
  xns:
    | XNSActivityOptions
    | undefined;
  /** Configure patches, by default, patches are introduced in enabled mode */
  patches: Patch[];
}

/**
 * UpdateOptions identifies an rpc method as a Temporal update definition, and describes
 * available update configuration options
 */
export interface UpdateOptions {
  /** cli command overrides */
  cli:
    | CLICommandOptions
    | undefined;
  /** ID expression */
  id: string;
  /** Fully-qualified update name */
  name: string;
  /** Configure patches, by default, patches are introduced in enabled mode */
  patches: Patch[];
  /** Include validation hook */
  validate: boolean;
  /** Default wait policy if not specified */
  wait_for_stage: WaitPolicy;
  /** @deprecated */
  wait_policy: WaitPolicy;
  /** XNS can be used to configure default activity options for xns workflow executions */
  xns: XNSActivityOptions | undefined;
}

/**
 * WorkflowOptions identifies an rpc method as a Temporal workflow definition, and describes
 * available workflow configuration options
 */
export interface WorkflowOptions {
  /** cli command overrides */
  cli:
    | CLICommandOptions
    | undefined;
  /** Fully-qualified workflow name */
  name: string;
  /**
   * List of additional names to register the workflow under. This can be used to migrate
   * to new naming conventions without breaking workflow history or existing clients.
   */
  aliases: string[];
  /** Queries supported by this workflow */
  query: WorkflowOptions_Query[];
  /** Signals supported by this workflow */
  signal: WorkflowOptions_Signal[];
  /** Updates supported by this workflow */
  update: WorkflowOptions_Update[];
  /** Request eager execution for this workflow, if a local worker is available. */
  enable_eager_start: boolean;
  /**
   * The timeout for duration of workflow execution.
   * It includes retries and continue as new. Use WorkflowRunTimeout to limit execution time
   * of a single workflow run.
   */
  execution_timeout:
    | Duration
    | undefined;
  /** Id expression */
  id: string;
  /** Whether server allow reuse of workflow ID */
  id_reuse_policy: IDReusePolicy;
  /**
   * Specifies default namespace for child workflows
   *
   * @deprecated
   */
  namespace: string;
  /** Nexus operation options */
  nexus:
    | NexusOperationOptions
    | undefined;
  /** Specifies a default parent close policy for child workflows */
  parent_close_policy: ParentClosePolicy;
  /** Configure patches, by default, patches are introduced in enabled mode */
  patches: Patch[];
  /** Specifies how to retry an Workflow if an error occurs */
  retry_policy:
    | RetryPolicy
    | undefined;
  /** The timeout for duration of a single workflow run. */
  run_timeout:
    | Duration
    | undefined;
  /** Bloblang mapping defining default workflow search attributes */
  search_attributes: string;
  /** Override service task queue */
  task_queue: string;
  /**
   * The timeout for processing workflow task from the time the worker
   * pulled this task. If a workflow task is lost, it is retried after this timeout.
   * The resolution is seconds.
   */
  task_timeout:
    | Duration
    | undefined;
  /**
   * Bloblang mapping defining default workflow typed search attributes. The mapping should be a map of
   * search attribute types to a map of search attribute keys to values.
   * Example:
   * string.foo = "bar"
   * string.baz = "qux"
   * float64.min = 123.0
   * int64.max = 456
   * time.created_at = now()
   * bool.is_active = true
   * keyword.name = "John Doe"
   * keyword_list.tags = ["foo", "bar"]
   */
  typed_search_attributes: string;
  /** Provides a Versioning Behavior to workflows of this type. */
  versioning_behavior: VersioningBehavior;
  /**
   * WaitForCancellation specifies whether to wait for canceled child workflow to be ended
   * (child workflow can be ended as: completed/failed/timedout/terminated/canceled)
   */
  wait_for_cancellation: boolean;
  /** Default workflow id conflict policy for start workflow with options */
  workflow_id_conflict_policy: WorkflowIdConflictPolicy;
  /** XNS can be used to configure default activity options for xns workflow executions */
  xns:
    | XNSActivityOptions
    | undefined;
  /**
   * Specifies distribution of work within a task queue
   * using Task Queue Priority and Task Queue Fairness
   */
  priority: Priority | undefined;
}

/** Query identifies a query supported by the worklow */
export interface WorkflowOptions_Query {
  /** Query name */
  ref: string;
  /** XNS can be used to configure default activity options for xns workflow executions */
  xns: XNSActivityOptions | undefined;
}

/** Signal identifies a signal supported by the workflow */
export interface WorkflowOptions_Signal {
  cli:
    | CLICommandOptions
    | undefined;
  /** Signal name */
  ref: string;
  /** Include convenience method for signal with start */
  start: boolean;
  /** XNS can be used to configure default activity options for xns workflow executions */
  xns: XNSActivityOptions | undefined;
}

/** Update identifies an update supported by the workflow */
export interface WorkflowOptions_Update {
  cli:
    | CLICommandOptions
    | undefined;
  /** Update name */
  ref: string;
  /** Include convenience method for update with start */
  start: boolean;
  /** Include convenience method for update with start and validation */
  validate?:
    | boolean
    | undefined;
  /** Default workflow id conflict policy for update with start */
  workflow_id_conflict_policy: WorkflowIdConflictPolicy;
  /** XNS can be used to configure default activity options for xns workflow executions */
  xns: XNSActivityOptions | undefined;
}

export interface XNSActivityOptions {
  /** Fully-qualified xns activity name */
  name: string;
  /** Override default task queue for activity */
  task_queue: string;
  /** Total time that a workflow is willing to wait for Activity to complete */
  schedule_to_close_timeout:
    | Duration
    | undefined;
  /**
   * Time that the Activity Task can stay in the Task Queue before it is picked up by
   * a Worker
   */
  schedule_to_start_timeout:
    | Duration
    | undefined;
  /** Maximum time of a single Activity execution attempt */
  start_to_close_timeout:
    | Duration
    | undefined;
  /** HeartbeatInterval configures the default heartbeat interval */
  heartbeat_interval:
    | Duration
    | undefined;
  /** Heartbeat timeout. Activity must call Activity.RecordHeartbeat(ctx, "my-heartbeat") */
  heartbeat_timeout:
    | Duration
    | undefined;
  /** Specifies how to retry an Activity if an error occurs */
  retry_policy:
    | RetryPolicy
    | undefined;
  /** Specifies how activity cancellation is propagated for xns activities that support it */
  parent_close_policy: ParentClosePolicy;
}
