// Code generated by protoc-gen-go_temporal. DO NOT EDIT.
// versions:
//
//	protoc-gen-go_temporal dev (latest)
//	protoc (unknown)
//
// source: kontra/v1/actor_service.proto
package kontrav1

import (
	"context"
	"errors"
	"fmt"
	expression "github.com/cludden/protoc-gen-go-temporal/pkg/expression"
	helpers "github.com/cludden/protoc-gen-go-temporal/pkg/helpers"
	enumsv1 "go.temporal.io/api/enums/v1"
	client "go.temporal.io/sdk/client"
	converter "go.temporal.io/sdk/converter"
	temporal "go.temporal.io/sdk/temporal"
	testsuite "go.temporal.io/sdk/testsuite"
	worker "go.temporal.io/sdk/worker"
	workflow "go.temporal.io/sdk/workflow"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"
)

// ActorServiceTaskQueue is the default task-queue for a kontra.v1.ActorService worker
var ActorServiceTaskQueue = "kontra-actor"

// kontra.v1.ActorService workflow names
const (
	RunWorkflowName = "kontra.v1.ActorService.Run"
)

// kontra.v1.ActorService workflow id expressions
var (
	RunIdexpression = expression.MustParseExpression("actor-${!idempotency_key.or(run_id).or(\"run\")}")
)

// ActorServiceClient describes a client for a(n) kontra.v1.ActorService worker
type ActorServiceClient interface {
	// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
	Run(ctx context.Context, req *EntryInput, opts ...*RunOptions) (*BareRef, error)

	// RunAsync starts a(n) kontra.v1.ActorService.Run workflow and returns a handle to the workflow run
	RunAsync(ctx context.Context, req *EntryInput, opts ...*RunOptions) (RunRun, error)

	// GetRun retrieves a handle to an existing kontra.v1.ActorService.Run workflow execution
	GetRun(ctx context.Context, workflowID string, runID string) RunRun

	// CancelWorkflow requests cancellation of an existing workflow execution
	CancelWorkflow(ctx context.Context, workflowID string, runID string) error

	// TerminateWorkflow an existing workflow execution
	TerminateWorkflow(ctx context.Context, workflowID string, runID string, reason string, details ...interface{}) error
}

// actorServiceClient implements a temporal client for a kontra.v1.ActorService service
type actorServiceClient struct {
	client client.Client
	log    *slog.Logger
}

// NewActorServiceClient initializes a new kontra.v1.ActorService client
func NewActorServiceClient(c client.Client, options ...*actorServiceClientOptions) ActorServiceClient {
	var cfg *actorServiceClientOptions
	if len(options) > 0 {
		cfg = options[0]
	} else {
		cfg = NewActorServiceClientOptions()
	}
	return &actorServiceClient{
		client: c,
		log:    cfg.getLogger(),
	}
}

// NewActorServiceClientWithOptions initializes a new ActorService client with the given options
func NewActorServiceClientWithOptions(c client.Client, opts client.Options, options ...*actorServiceClientOptions) (ActorServiceClient, error) {
	var err error
	c, err = client.NewClientFromExisting(c, opts)
	if err != nil {
		return nil, fmt.Errorf("error initializing client with options: %w", err)
	}
	var cfg *actorServiceClientOptions
	if len(options) > 0 {
		cfg = options[0]
	} else {
		cfg = NewActorServiceClientOptions()
	}
	return &actorServiceClient{
		client: c,
		log:    cfg.getLogger(),
	}, nil
}

// actorServiceClientOptions describes optional runtime configuration for a ActorServiceClient
type actorServiceClientOptions struct {
	log *slog.Logger
}

// NewActorServiceClientOptions initializes a new actorServiceClientOptions value
func NewActorServiceClientOptions() *actorServiceClientOptions {
	return &actorServiceClientOptions{}
}

// WithLogger can be used to override the default logger
func (opts *actorServiceClientOptions) WithLogger(l *slog.Logger) *actorServiceClientOptions {
	if l != nil {
		opts.log = l
	}
	return opts
}

// getLogger returns the configured logger, or the default logger
func (opts *actorServiceClientOptions) getLogger() *slog.Logger {
	if opts != nil && opts.log != nil {
		return opts.log
	}
	return slog.Default()
}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
func (c *actorServiceClient) Run(ctx context.Context, req *EntryInput, options ...*RunOptions) (*BareRef, error) {
	run, err := c.RunAsync(ctx, req, options...)
	if err != nil {
		return nil, err
	}
	return run.Get(ctx)
}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
func (c *actorServiceClient) RunAsync(ctx context.Context, req *EntryInput, options ...*RunOptions) (RunRun, error) {
	var o *RunOptions
	if len(options) > 0 && options[0] != nil {
		o = options[0]
	} else {
		o = NewRunOptions()
	}
	opts, err := o.Build(req.ProtoReflect())
	if err != nil {
		return nil, fmt.Errorf("error initializing client.StartWorkflowOptions: %w", err)
	}
	run, err := c.client.ExecuteWorkflow(ctx, opts, RunWorkflowName, req)
	if err != nil {
		return nil, err
	}
	if run == nil {
		return nil, errors.New("execute workflow returned nil run")
	}
	return &runRun{
		client: c,
		run:    run,
	}, nil
}

// GetRun fetches an existing kontra.v1.ActorService.Run execution
func (c *actorServiceClient) GetRun(ctx context.Context, workflowID string, runID string) RunRun {
	return &runRun{
		client: c,
		run:    c.client.GetWorkflow(ctx, workflowID, runID),
	}
}

// CancelWorkflow requests cancellation of an existing workflow execution
func (c *actorServiceClient) CancelWorkflow(ctx context.Context, workflowID string, runID string) error {
	return c.client.CancelWorkflow(ctx, workflowID, runID)
}

// TerminateWorkflow terminates an existing workflow execution
func (c *actorServiceClient) TerminateWorkflow(ctx context.Context, workflowID string, runID string, reason string, details ...interface{}) error {
	return c.client.TerminateWorkflow(ctx, workflowID, runID, reason, details...)
}

// RunOptions provides configuration for a kontra.v1.ActorService.Run workflow operation
type RunOptions struct {
	options                  client.StartWorkflowOptions
	executionTimeout         *time.Duration
	id                       *string
	idReusePolicy            enumsv1.WorkflowIdReusePolicy
	priority                 *temporal.Priority
	priorityKey              *int
	fairnessKey              *string
	fairnessWeight           *float32
	retryPolicy              *temporal.RetryPolicy
	runTimeout               *time.Duration
	searchAttributes         map[string]any
	taskQueue                *string
	taskTimeout              *time.Duration
	typedSearchAttributes    *temporal.SearchAttributes
	enableEagerStart         *bool
	workflowIdConflictPolicy enumsv1.WorkflowIdConflictPolicy
}

// NewRunOptions initializes a new RunOptions value
func NewRunOptions() *RunOptions {
	return &RunOptions{}
}

// Build initializes a new go.temporal.io/sdk/client.StartWorkflowOptions value with defaults and overrides applied
func (o *RunOptions) Build(req protoreflect.Message) (client.StartWorkflowOptions, error) {
	opts := o.options
	if v := o.id; v != nil {
		opts.ID = *v
	} else if opts.ID == "" {
		id, err := expression.EvalExpression(RunIdexpression, req)
		if err != nil {
			return opts, fmt.Errorf("error evaluating id expression for %q workflow: %w", RunWorkflowName, err)
		}
		opts.ID = id
	}
	if v := o.idReusePolicy; v != enumsv1.WORKFLOW_ID_REUSE_POLICY_UNSPECIFIED {
		opts.WorkflowIDReusePolicy = v
	}
	if v := o.workflowIdConflictPolicy; v != enumsv1.WORKFLOW_ID_CONFLICT_POLICY_UNSPECIFIED {
		opts.WorkflowIDConflictPolicy = v
	}
	if v := o.taskQueue; v != nil {
		opts.TaskQueue = *v
	} else if opts.TaskQueue == "" {
		opts.TaskQueue = ActorServiceTaskQueue
	}
	if v := o.retryPolicy; v != nil {
		opts.RetryPolicy = v
	}
	if v := o.searchAttributes; v != nil {
		opts.SearchAttributes = o.searchAttributes
	}
	if v := o.typedSearchAttributes; v != nil {
		opts.TypedSearchAttributes = *v
	}
	if v := o.priority; v != nil {
		opts.Priority = *v
	}
	if v := o.priorityKey; v != nil {
		opts.Priority.PriorityKey = *v
	}
	if v := o.fairnessKey; v != nil {
		opts.Priority.FairnessKey = *v
	}
	if v := o.fairnessWeight; v != nil {
		opts.Priority.FairnessWeight = *v
	}
	if v := o.enableEagerStart; v != nil {
		opts.EnableEagerStart = *v
	}
	if v := o.executionTimeout; v != nil {
		opts.WorkflowExecutionTimeout = *v
	}
	if v := o.runTimeout; v != nil {
		opts.WorkflowRunTimeout = *v
	}
	if v := o.taskTimeout; v != nil {
		opts.WorkflowTaskTimeout = *v
	}
	return opts, nil
}

// WithStartWorkflowOptions sets the initial go.temporal.io/sdk/client.StartWorkflowOptions
func (o *RunOptions) WithStartWorkflowOptions(options client.StartWorkflowOptions) *RunOptions {
	o.options = options
	return o
}

// WithEnableEagerStart sets the EnableEagerStart value
func (o *RunOptions) WithEnableEagerStart(enable bool) *RunOptions {
	o.enableEagerStart = &enable
	return o
}

// WithExecutionTimeout sets the WorkflowExecutionTimeout value
func (o *RunOptions) WithExecutionTimeout(d time.Duration) *RunOptions {
	o.executionTimeout = &d
	return o
}

// WithID sets the ID value
func (o *RunOptions) WithID(id string) *RunOptions {
	o.id = &id
	return o
}

// WithIDReusePolicy sets the WorkflowIDReusePolicy value
func (o *RunOptions) WithIDReusePolicy(policy enumsv1.WorkflowIdReusePolicy) *RunOptions {
	o.idReusePolicy = policy
	return o
}

// WithPriority sets the Priority value
func (o *RunOptions) WithPriority(priority temporal.Priority) *RunOptions {
	o.priority = &priority
	return o
}

// WithPriorityKey sets the Priority.PriorityKey value, overriding any schema default while leaving other Priority fields intact
func (o *RunOptions) WithPriorityKey(priorityKey int) *RunOptions {
	o.priorityKey = &priorityKey
	return o
}

// WithFairnessKey sets the Priority.FairnessKey value, overriding any schema default while leaving other Priority fields intact
func (o *RunOptions) WithFairnessKey(fairnessKey string) *RunOptions {
	o.fairnessKey = &fairnessKey
	return o
}

// WithFairnessWeight sets the Priority.FairnessWeight value, overriding any schema default while leaving other Priority fields intact
func (o *RunOptions) WithFairnessWeight(fairnessWeight float32) *RunOptions {
	o.fairnessWeight = &fairnessWeight
	return o
}

// WithRetryPolicy sets the RetryPolicy value
func (o *RunOptions) WithRetryPolicy(policy *temporal.RetryPolicy) *RunOptions {
	o.retryPolicy = policy
	return o
}

// WithRunTimeout sets the WorkflowRunTimeout value
func (o *RunOptions) WithRunTimeout(d time.Duration) *RunOptions {
	o.runTimeout = &d
	return o
}

// WithSearchAttributes sets the SearchAttributes value
func (o *RunOptions) WithSearchAttributes(sa map[string]any) *RunOptions {
	o.searchAttributes = sa
	return o
}

// WithTaskTimeout sets the WorkflowTaskTimeout value
func (o *RunOptions) WithTaskTimeout(d time.Duration) *RunOptions {
	o.taskTimeout = &d
	return o
}

// WithTaskQueue sets the TaskQueue value
func (o *RunOptions) WithTaskQueue(tq string) *RunOptions {
	o.taskQueue = &tq
	return o
}

// WithTypedSearchAttributes sets the TypedSearchAttributes value
func (o *RunOptions) WithTypedSearchAttributes(tsa temporal.SearchAttributes) *RunOptions {
	o.typedSearchAttributes = &tsa
	return o
}

// WithWorkflowIdConflictPolicy sets the WorkflowIdConflictPolicy value
func (o *RunOptions) WithWorkflowIdConflictPolicy(policy enumsv1.WorkflowIdConflictPolicy) *RunOptions {
	o.workflowIdConflictPolicy = policy
	return o
}

// RunRun describes a(n) kontra.v1.ActorService.Run workflow run
type RunRun interface {
	// ID returns the workflow ID
	ID() string

	// RunID returns the workflow instance ID
	RunID() string

	// Run returns the inner client.WorkflowRun
	Run() client.WorkflowRun

	// Get blocks until the workflow is complete and returns the result
	Get(ctx context.Context) (*BareRef, error)

	// Cancel requests cancellation of a workflow in execution, returning an error if applicable
	Cancel(ctx context.Context) error

	// Terminate terminates a workflow in execution, returning an error if applicable
	Terminate(ctx context.Context, reason string, details ...interface{}) error
}

// runRun provides an internal implementation of a(n) RunRunRun
type runRun struct {
	client *actorServiceClient
	run    client.WorkflowRun
}

// ID returns the workflow ID
func (r *runRun) ID() string {
	return r.run.GetID()
}

// Run returns the inner client.WorkflowRun
func (r *runRun) Run() client.WorkflowRun {
	return r.run
}

// RunID returns the execution ID
func (r *runRun) RunID() string {
	return r.run.GetRunID()
}

// Cancel requests cancellation of a workflow in execution, returning an error if applicable
func (r *runRun) Cancel(ctx context.Context) error {
	return r.client.CancelWorkflow(ctx, r.ID(), r.RunID())
}

// Get blocks until the workflow is complete, returning the result if applicable
func (r *runRun) Get(ctx context.Context) (*BareRef, error) {
	var resp BareRef
	if err := r.run.Get(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Terminate terminates a workflow in execution, returning an error if applicable
func (r *runRun) Terminate(ctx context.Context, reason string, details ...interface{}) error {
	return r.client.TerminateWorkflow(ctx, r.ID(), r.RunID(), reason, details...)
}

// Reference to generated workflow functions
var (
	// actorServiceRegistrationMutex is a mutex for registering kontra.v1.ActorService workflows
	actorServiceRegistrationMutex sync.Mutex
	// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
	RunFunction func(workflow.Context, *EntryInput) (*BareRef, error)
)

// ActorServiceWorkflowFunctions describes a mockable dependency for inlining workflows within other workflows
type (
	// ActorServiceWorkflowFunctions describes a mockable dependency for inlining workflows within other workflows
	ActorServiceWorkflowFunctions interface {
		// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
		Run(workflow.Context, *EntryInput) (*BareRef, error)
	}
	// actorServiceWorkflowFunctions provides an internal ActorServiceWorkflowFunctions implementation
	actorServiceWorkflowFunctions struct{}
)

func NewActorServiceWorkflowFunctions() ActorServiceWorkflowFunctions {
	return &actorServiceWorkflowFunctions{}
}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
func (f *actorServiceWorkflowFunctions) Run(ctx workflow.Context, req *EntryInput) (*BareRef, error) {
	if RunFunction == nil {
		return nil, errors.New("Run requires workflow registration via RegisterActorServiceWorkflows or RegisterRunWorkflow")
	}
	return RunFunction(ctx, req)
}

// ActorServiceWorkflows provides methods for initializing new kontra.v1.ActorService workflow values
type ActorServiceWorkflows interface {
	// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
	Run(ctx workflow.Context, input *RunWorkflowInput) (RunWorkflow, error)
}

// RegisterActorServiceWorkflows registers kontra.v1.ActorService workflows with the given worker
func RegisterActorServiceWorkflows(r worker.WorkflowRegistry, workflows ActorServiceWorkflows) {
	RegisterRunWorkflow(r, workflows.Run)
}

// RegisterRunWorkflow registers a kontra.v1.ActorService.Run workflow with the given worker
func RegisterRunWorkflow(r worker.WorkflowRegistry, wf func(workflow.Context, *RunWorkflowInput) (RunWorkflow, error)) {
	actorServiceRegistrationMutex.Lock()
	defer actorServiceRegistrationMutex.Unlock()
	RunFunction = buildRun(wf)
	r.RegisterWorkflowWithOptions(RunFunction, workflow.RegisterOptions{Name: RunWorkflowName})
}

// buildRun converts a Run workflow struct into a valid workflow function
func buildRun(ctor func(workflow.Context, *RunWorkflowInput) (RunWorkflow, error)) func(workflow.Context, *EntryInput) (*BareRef, error) {
	return func(ctx workflow.Context, req *EntryInput) (*BareRef, error) {
		input := &RunWorkflowInput{
			Req: req,
		}
		wf, err := ctor(ctx, input)
		if err != nil {
			return nil, err
		}
		if initializable, ok := wf.(helpers.Initializable); ok {
			if err := initializable.Initialize(ctx); err != nil {
				return nil, err
			}
		}
		return wf.Execute(ctx)
	}
}

// RunWorkflowInput describes the input to a(n) kontra.v1.ActorService.Run workflow constructor
type RunWorkflowInput struct {
	Req *EntryInput
}

// ContinueAsNew returns an appropriately configured ContinueAsNewError
func (i *RunWorkflowInput) ContinueAsNew(ctx workflow.Context, input *EntryInput, options ...workflow.ContinueAsNewErrorOptions) (*BareRef, error) {
	next := i.Req
	if input != nil {
		next = input
	}
	if len(options) > 0 {
		return nil, workflow.NewContinueAsNewErrorWithOptions(ctx, options[0], RunWorkflowName, next)
	}
	return nil, workflow.NewContinueAsNewError(ctx, RunWorkflowName, next)
}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
//
// workflow details: (name: "kontra.v1.ActorService.Run", id: "actor-${!idempotency_key.or(run_id).or("run")}")
type RunWorkflow interface {
	// Execute defines the entrypoint to a(n) kontra.v1.ActorService.Run workflow
	Execute(ctx workflow.Context) (*BareRef, error)
}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
func RunChild(ctx workflow.Context, req *EntryInput, options ...*RunChildOptions) (*BareRef, error) {
	childRun, err := RunChildAsync(ctx, req, options...)
	if err != nil {
		return nil, err
	}
	return childRun.Get(ctx)
}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
func RunChildAsync(ctx workflow.Context, req *EntryInput, options ...*RunChildOptions) (*RunChildRun, error) {
	var o *RunChildOptions
	if len(options) > 0 && options[0] != nil {
		o = options[0]
	} else {
		o = NewRunChildOptions()
	}
	opts, err := o.Build(ctx, req.ProtoReflect())
	if err != nil {
		return nil, fmt.Errorf("error initializing workflow.ChildWorkflowOptions: %w", err)
	}
	ctx = workflow.WithChildOptions(ctx, opts)
	if o.dc != nil {
		ctx = workflow.WithDataConverter(ctx, o.dc)
	}
	return &RunChildRun{Future: workflow.ExecuteChildWorkflow(ctx, RunWorkflowName, req)}, nil
}

// RunChildOptions provides configuration for a child kontra.v1.ActorService.Run workflow operation
type RunChildOptions struct {
	options               workflow.ChildWorkflowOptions
	executionTimeout      *time.Duration
	id                    *string
	idReusePolicy         enumsv1.WorkflowIdReusePolicy
	priority              *temporal.Priority
	priorityKey           *int
	fairnessKey           *string
	fairnessWeight        *float32
	retryPolicy           *temporal.RetryPolicy
	runTimeout            *time.Duration
	searchAttributes      map[string]any
	taskQueue             *string
	taskTimeout           *time.Duration
	typedSearchAttributes *temporal.SearchAttributes
	dc                    converter.DataConverter
	parentClosePolicy     enumsv1.ParentClosePolicy
	waitForCancellation   *bool
}

// NewRunChildOptions initializes a new RunChildOptions value
func NewRunChildOptions() *RunChildOptions {
	return &RunChildOptions{}
}

// Build initializes a new go.temporal.io/sdk/workflow.ChildWorkflowOptions value with defaults and overrides applied
func (o *RunChildOptions) Build(ctx workflow.Context, req protoreflect.Message) (workflow.ChildWorkflowOptions, error) {
	opts := o.options
	if v := o.id; v != nil {
		opts.WorkflowID = *v
	} else if opts.WorkflowID == "" {
		// wrap expression evaluation in local activity
		// more info: https://cludden.github.io/protoc-gen-go-temporal/docs/guides/patches#pv_64-expression-evaluation-local-activity
		if workflow.GetVersion(ctx, "cludden_protoc-gen-go-temporal_64_expression-evaluation-local-activity", workflow.DefaultVersion, 1) == 1 {
			lao := workflow.GetLocalActivityOptions(ctx)
			lao.ScheduleToCloseTimeout = time.Second * 10
			if err := workflow.ExecuteLocalActivity(workflow.WithLocalActivityOptions(ctx, lao), func(ctx context.Context) (string, error) {
				id, err := expression.EvalExpression(RunIdexpression, req)
				if err != nil {
					return "", fmt.Errorf("error evaluating id expression for %q workflow: %w", RunWorkflowName, err)
				}
				return id, nil
			}).Get(ctx, &opts.WorkflowID); err != nil {
				return opts, fmt.Errorf("error evaluating id expression for %q workflow: %w", RunWorkflowName, err)
			}
		} else {
			id, err := expression.EvalExpression(RunIdexpression, req)
			if err != nil {
				return opts, fmt.Errorf("error evaluating id expression for %q workflow: %w", RunWorkflowName, err)
			}
			opts.WorkflowID = id
		}
	}
	if v := o.idReusePolicy; v != enumsv1.WORKFLOW_ID_REUSE_POLICY_UNSPECIFIED {
		opts.WorkflowIDReusePolicy = v
	}
	if v := o.taskQueue; v != nil {
		opts.TaskQueue = *v
	} else if opts.TaskQueue == "" {
		opts.TaskQueue = ActorServiceTaskQueue
	}
	if v := o.retryPolicy; v != nil {
		opts.RetryPolicy = v
	}
	if v := o.searchAttributes; v != nil {
		opts.SearchAttributes = o.searchAttributes
	}
	if v := o.typedSearchAttributes; v != nil {
		opts.TypedSearchAttributes = *v
	}
	if v := o.priority; v != nil {
		opts.Priority = *v
	}
	if v := o.priorityKey; v != nil {
		opts.Priority.PriorityKey = *v
	}
	if v := o.fairnessKey; v != nil {
		opts.Priority.FairnessKey = *v
	}
	if v := o.fairnessWeight; v != nil {
		opts.Priority.FairnessWeight = *v
	}
	if v := o.executionTimeout; v != nil {
		opts.WorkflowExecutionTimeout = *v
	}
	if v := o.runTimeout; v != nil {
		opts.WorkflowRunTimeout = *v
	}
	if v := o.taskTimeout; v != nil {
		opts.WorkflowTaskTimeout = *v
	}
	if v := o.parentClosePolicy; v != enumsv1.PARENT_CLOSE_POLICY_UNSPECIFIED {
		opts.ParentClosePolicy = v
	}
	if v := o.waitForCancellation; v != nil {
		opts.WaitForCancellation = *v
	}
	return opts, nil
}

// WithChildWorkflowOptions sets the initial go.temporal.io/sdk/workflow.ChildWorkflowOptions
func (o *RunChildOptions) WithChildWorkflowOptions(options workflow.ChildWorkflowOptions) *RunChildOptions {
	o.options = options
	return o
}

// WithDataConverter registers a DataConverter for the child workflow
func (o *RunChildOptions) WithDataConverter(dc converter.DataConverter) *RunChildOptions {
	o.dc = dc
	return o
}

// WithExecutionTimeout sets the WorkflowExecutionTimeout value
func (o *RunChildOptions) WithExecutionTimeout(d time.Duration) *RunChildOptions {
	o.executionTimeout = &d
	return o
}

// WithID sets the WorkflowID value
func (o *RunChildOptions) WithID(id string) *RunChildOptions {
	o.id = &id
	return o
}

// WithIDReusePolicy sets the WorkflowIDReusePolicy value
func (o *RunChildOptions) WithIDReusePolicy(policy enumsv1.WorkflowIdReusePolicy) *RunChildOptions {
	o.idReusePolicy = policy
	return o
}

// WithParentClosePolicy sets the WorkflowIDReusePolicy value
func (o *RunChildOptions) WithParentClosePolicy(policy enumsv1.ParentClosePolicy) *RunChildOptions {
	o.parentClosePolicy = policy
	return o
}

// WithPriority sets the Priority value
func (o *RunChildOptions) WithPriority(priority temporal.Priority) *RunChildOptions {
	o.priority = &priority
	return o
}

// WithPriorityKey sets the Priority.PriorityKey value, overriding any schema default while leaving other Priority fields intact
func (o *RunChildOptions) WithPriorityKey(priorityKey int) *RunChildOptions {
	o.priorityKey = &priorityKey
	return o
}

// WithFairnessKey sets the Priority.FairnessKey value, overriding any schema default while leaving other Priority fields intact
func (o *RunChildOptions) WithFairnessKey(fairnessKey string) *RunChildOptions {
	o.fairnessKey = &fairnessKey
	return o
}

// WithFairnessWeight sets the Priority.FairnessWeight value, overriding any schema default while leaving other Priority fields intact
func (o *RunChildOptions) WithFairnessWeight(fairnessWeight float32) *RunChildOptions {
	o.fairnessWeight = &fairnessWeight
	return o
}

// WithRetryPolicy sets the RetryPolicy value
func (o *RunChildOptions) WithRetryPolicy(policy *temporal.RetryPolicy) *RunChildOptions {
	o.retryPolicy = policy
	return o
}

// WithRunTimeout sets the WorkflowRunTimeout value
func (o *RunChildOptions) WithRunTimeout(d time.Duration) *RunChildOptions {
	o.runTimeout = &d
	return o
}

// WithSearchAttributes sets the SearchAttributes value
func (o *RunChildOptions) WithSearchAttributes(sa map[string]any) *RunChildOptions {
	o.searchAttributes = sa
	return o
}

// WithTaskTimeout sets the WorkflowTaskTimeout value
func (o *RunChildOptions) WithTaskTimeout(d time.Duration) *RunChildOptions {
	o.taskTimeout = &d
	return o
}

// WithTaskQueue sets the TaskQueue value
func (o *RunChildOptions) WithTaskQueue(tq string) *RunChildOptions {
	o.taskQueue = &tq
	return o
}

// WithTypedSearchAttributes sets the TypedSearchAttributes value
func (o *RunChildOptions) WithTypedSearchAttributes(tsa temporal.SearchAttributes) *RunChildOptions {
	o.typedSearchAttributes = &tsa
	return o
}

// WithWaitForCancellation sets the WaitForCancellation value
func (o *RunChildOptions) WithWaitForCancellation(wait bool) *RunChildOptions {
	o.waitForCancellation = &wait
	return o
}

// RunChildRun describes a child Run workflow run
type RunChildRun struct {
	Future workflow.ChildWorkflowFuture
}

// Get blocks until the workflow is completed, returning the response value
func (r *RunChildRun) Get(ctx workflow.Context) (*BareRef, error) {
	var resp BareRef
	if err := r.Future.Get(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Select adds this completion to the selector. Callback can be nil.
func (r *RunChildRun) Select(sel workflow.Selector, fn func(*RunChildRun)) workflow.Selector {
	return sel.AddFuture(r.Future, func(workflow.Future) {
		if fn != nil {
			fn(r)
		}
	})
}

// SelectStart adds waiting for start to the selector. Callback can be nil.
func (r *RunChildRun) SelectStart(sel workflow.Selector, fn func(*RunChildRun)) workflow.Selector {
	return sel.AddFuture(r.Future.GetChildWorkflowExecution(), func(workflow.Future) {
		if fn != nil {
			fn(r)
		}
	})
}

// WaitStart waits for the child workflow to start
func (r *RunChildRun) WaitStart(ctx workflow.Context) (*workflow.Execution, error) {
	var exec workflow.Execution
	if err := r.Future.GetChildWorkflowExecution().Get(ctx, &exec); err != nil {
		return nil, err
	}
	return &exec, nil
}

// ActorServiceActivities describes available worker activities
type ActorServiceActivities interface{}

// RegisterActorServiceActivities registers activities with a worker
func RegisterActorServiceActivities(r worker.ActivityRegistry, activities ActorServiceActivities) {}

// TestClient provides a testsuite-compatible Client
type TestActorServiceClient struct {
	env       *testsuite.TestWorkflowEnvironment
	workflows ActorServiceWorkflows
}

var _ ActorServiceClient = &TestActorServiceClient{}

// NewTestActorServiceClient initializes a new TestActorServiceClient value
func NewTestActorServiceClient(env *testsuite.TestWorkflowEnvironment, workflows ActorServiceWorkflows, activities ActorServiceActivities) *TestActorServiceClient {
	if workflows != nil {
		RegisterActorServiceWorkflows(env, workflows)
	}
	if activities != nil {
		RegisterActorServiceActivities(env, activities)
	}
	return &TestActorServiceClient{env, workflows}
}

// Run executes a(n) kontra.v1.ActorService.Run workflow in the test environment
func (c *TestActorServiceClient) Run(ctx context.Context, req *EntryInput, opts ...*RunOptions) (*BareRef, error) {
	run, err := c.RunAsync(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return run.Get(ctx)
}

// RunAsync executes a(n) kontra.v1.ActorService.Run workflow in the test environment
func (c *TestActorServiceClient) RunAsync(ctx context.Context, req *EntryInput, options ...*RunOptions) (RunRun, error) {
	var o *RunOptions
	if len(options) > 0 && options[0] != nil {
		o = options[0]
	} else {
		o = NewRunOptions()
	}
	opts, err := o.Build(req.ProtoReflect())
	if err != nil {
		return nil, fmt.Errorf("error initializing client.StartWorkflowOptions: %w", err)
	}
	return &testRunRun{client: c, env: c.env, opts: &opts, req: req, workflows: c.workflows}, nil
}

// GetRun is a noop
func (c *TestActorServiceClient) GetRun(ctx context.Context, workflowID string, runID string) RunRun {
	return &testRunRun{env: c.env, workflows: c.workflows}
}

// CancelWorkflow requests cancellation of an existing workflow execution
func (c *TestActorServiceClient) CancelWorkflow(ctx context.Context, workflowID string, runID string) error {
	c.env.CancelWorkflow()
	return nil
}

// TerminateWorkflow terminates an existing workflow execution
func (c *TestActorServiceClient) TerminateWorkflow(ctx context.Context, workflowID string, runID string, reason string, details ...interface{}) error {
	return c.CancelWorkflow(ctx, workflowID, runID)
}

var _ RunRun = &testRunRun{}

// testRunRun provides convenience methods for interacting with a(n) kontra.v1.ActorService.Run workflow in the test environment
type testRunRun struct {
	client    *TestActorServiceClient
	env       *testsuite.TestWorkflowEnvironment
	isStarted atomic.Bool
	opts      *client.StartWorkflowOptions
	req       *EntryInput
	workflows ActorServiceWorkflows
}

// Cancel requests cancellation of a workflow in execution, returning an error if applicable
func (r *testRunRun) Cancel(ctx context.Context) error {
	return r.client.CancelWorkflow(ctx, r.ID(), r.RunID())
}

// Get retrieves a test kontra.v1.ActorService.Run workflow result
func (r *testRunRun) Get(context.Context) (*BareRef, error) {
	if r.isStarted.CompareAndSwap(false, true) {
		r.env.ExecuteWorkflow(RunWorkflowName, r.req)
	}
	if !r.env.IsWorkflowCompleted() {
		return nil, errors.New("workflow in progress")
	}
	if err := r.env.GetWorkflowError(); err != nil {
		return nil, err
	}
	var result BareRef
	if err := r.env.GetWorkflowResult(&result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ID returns a test kontra.v1.ActorService.Run workflow run's workflow ID
func (r *testRunRun) ID() string {
	if r.opts != nil {
		return r.opts.ID
	}
	return ""
}

// Run noop implementation
func (r *testRunRun) Run() client.WorkflowRun {
	return nil
}

// RunID noop implementation
func (r *testRunRun) RunID() string {
	return ""
}

// Terminate terminates a workflow in execution, returning an error if applicable
func (r *testRunRun) Terminate(ctx context.Context, reason string, details ...interface{}) error {
	return r.client.TerminateWorkflow(ctx, r.ID(), r.RunID(), reason, details...)
}
