// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kontra/v1/catalog.proto

package kontrav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The cross-language ACTOR DESCRIPTOR — the `describe()` output every language SDK
// emits and the orchestrator catalog stores via POST /api/actors. This is the
// discovery contract: a (name, version) actor becomes visible to the graph editor and
// `pnpm dispatch` once its descriptor is registered.
//
// Per-actor I/O is JSON Schema (Draft 2020-12), NOT proto, so the operation schemas are
// opaque google.protobuf.Struct and not typed messages. The descriptor carries identity +
// the per-operation schemas only; it does not model what is inside them.
//
// NOTHING OUTSIDE THIS REPO OWNS THAT COMPATIBILITY. This header used to name an external
// schema registry (ADR 0008) as the owner of I/O compat, and no such service existed: none in
// docker-compose, no client, nothing calling one. A contract file asserting a component that
// does not exist is worse than silence, because it is the place a reader goes to find out who
// checks. Enforcement is in-process, where the schemas already are — ajv on the execution path
// (ADR 0003) and the immutability rule at registration (ADR 0004: a version is immutable, any
// I/O schema change bumps it). ADR 0027 deleted the registry and records what is genuinely
// lost with it: nothing compares one version's schema to the next.
//
// As with entry.proto, this is the shared TYPE DEFINITION the seams are checked against;
// the wire stays JSON (ADR 0002). Each SDK hand-emits that JSON — Go in
// runtime/go/registrar, Python in runtime/python/internals/catalog.py — and the
// orchestrator reads it in POST /api/actors and persists it as ActorRecord
// (control/orchestrator/src/db/repo.ts). Nothing makes those three agree except one check per side,
// each written where that side lives and sharing no code with the others:
// runtime/handler/internal/wire/wire_congruence_test.go reads the generated descriptor back through
// protoreflect, tests/test_method_types.py holds the posted Python body to it, and
// control/orchestrator/catalog.contract.ts makes a field this file defines and the store cannot hold
// a compile error.
//
// THOSE THREE CHECK EACH SIDE AGAINST THIS FILE, WHICH IS NOT THE SAME AS THE SIDES AGREEING.
// `source` was congruent with this file, present in the `actors` table and emitted by Python,
// and simply absent from the Go emitter — every check above stayed green while a catalogued Go
// actor had no way back to its code. What holds the emitters to EACH OTHER is one golden
// descriptor, shared/conformance/catalog.json, that all three compare their real emission to:
// runtime/go/registrar/conformance_test.go, tests/test_catalog_conformance.py and
// control/orchestrator/src/catalog.conformance.test.ts.
type ActorDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // "{name}@{version}" — the catalog primary key
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                  // immutable; bump on any I/O schema change (ADR 0004)
	SchemaVersion string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // "kontra.actor.v1"
	Operations    []*ActorOperation      `protobuf:"bytes,5,rep,name=operations,proto3" json:"operations,omitempty"`
	// OCI image digest the worker self-registers (ADR 0011); "" = unset/dev.
	Digest string `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`
	// The directory the WORKER loaded this actor from; "" = nothing said where.
	//
	// Nothing linked a registered actor back to its code. `.kontra/actors/` is where an
	// operator's own actors go and is usually empty — the catalogued ones were run from
	// `examples/` or a checkout somewhere — so the Actors page could list twenty-three actors
	// and offer no way to reach any of them. It is the path AS THE WORKER SAW IT, which on a
	// fleet Machine is `/opt/kontra/actor/<name>` and not a path on the reader's disk; that is
	// still the honest answer to where the actor came from.
	Source        string `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"` // appended (7): the numbers here are never reused or renumbered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorDescriptor) Reset() {
	*x = ActorDescriptor{}
	mi := &file_kontra_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorDescriptor) ProtoMessage() {}

func (x *ActorDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorDescriptor.ProtoReflect.Descriptor instead.
func (*ActorDescriptor) Descriptor() ([]byte, []int) {
	return file_kontra_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ActorDescriptor) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ActorDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActorDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ActorDescriptor) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ActorDescriptor) GetOperations() []*ActorOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ActorDescriptor) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ActorDescriptor) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// One operation an actor exposes — ONE PER METHOD (ADR 0023 §9).
//
// It used to be exactly one, named "run", because an Actor had exactly one entry point. An
// Actor now declares as many Methods as it has jobs and each carries its OWN signature:
// `fetch` takes a URL and emits a page while `title` takes a page, so a single Actor-level
// pair could only ever describe one of them. `name` is the Method name a caller dispatches.
//
// `params` stays ACTOR-level (run-wide config, not a signature) and rides on every operation.
//
// input/output are JSON Schema docs (Draft 2020-12), DERIVED from the types a Method declares
// with `takes=`/`emits=` — which are the same types the author's body reads and writes
// (`unit.value` is an instance of `takes`, `unit.emit(Emits(...))`). Unset for a Method that
// declares neither: it still registers and stays dispatchable by name, it simply advertises
// nothing.
type ActorOperation struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // the Method's dispatch name
	Params *structpb.Struct       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"` // run-wide config schema, or unset
	Input  *structpb.Struct       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`   // per-record input schema, or unset
	Output *structpb.Struct       `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"` // per-record output schema, or unset
	// What the Method is FOR, in the author's own words — a Go `Does("…")`, the first paragraph
	// of a Python docstring. A catalog of a name and two schemas can say what a Method TAKES and
	// never what it DOES, which leaves an operator composing one Actor's Method into another's
	// with nothing to compose from. "" = the author wrote none; both SDKs omit the JSON key
	// rather than sending an empty string, because undescribed and described-with-nothing render
	// differently and only one of them is actionable.
	//
	// Appended (5), declared last: field numbers here are APPEND-ONLY. Renumbering to put this
	// next to `name` would silently re-point every already-registered descriptor's fields.
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorOperation) Reset() {
	*x = ActorOperation{}
	mi := &file_kontra_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorOperation) ProtoMessage() {}

func (x *ActorOperation) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorOperation.ProtoReflect.Descriptor instead.
func (*ActorOperation) Descriptor() ([]byte, []int) {
	return file_kontra_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ActorOperation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActorOperation) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ActorOperation) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ActorOperation) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ActorOperation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// A CALLER WORKFLOW, described — the other half of a run, which today describes nothing.
//
// A Run is one execution of a caller's workflow (ADR 0023 §12): the workflow dispatches the
// actors, and the actors are the only side with a descriptor. `GET /api/workflows` lists
// `.kontra/workflows/*.py` by filename, byte count and mtime, so every surface that shows a
// workflow can say that a file exists and nothing about what it accepts, what it returns or
// what it is for — all three of which are already written down in the source, in the
// `@workflow.run` signature and the class docstring, and none of which survive to a reader.
//
// THE TYPE EXISTS BEFORE THE REGISTRATION PATH, deliberately. Nothing emits one yet. A shape
// invented in the same commit as the code that fills it is a shape nothing was checked
// against; this way the emitter has something to be wrong about.
//
// Same stance on schemas as ActorOperation: input/output are opaque JSON Schema (Draft
// 2020-12) documents derived from the types the run method declares, not proto messages.
type WorkflowDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workflow TYPE a caller starts — the `@workflow.defn` class name (`Ping`), which is
	// what `kontra workflow start` names and NOT the file it lives in. Two workflows can share
	// a file; the type is what Temporal routes on.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// What it is for, from the class docstring's first paragraph; "" = undescribed.
	Description string           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Input       *structpb.Struct `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`   // schema of the run argument, or unset
	Output      *structpb.Struct `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"` // schema of the return value, or unset
	// The task queue the registering worker is polling. "" = it did not say.
	//
	// THE OTHER HALF OF "HOW DO I START THIS". `name` is what Temporal routes ON; this is where it
	// routes TO. A start is accepted for any queue name and only a worker polling that exact one
	// takes the task, so the right type on the wrong queue is a run that starts, never progresses,
	// and reports `running` the whole time — or fails its workflow task against a worker that polls
	// that queue and does not know the type. Neither is visible as a wrong queue.
	//
	// The WORKER is the only honest source: it is about to poll this queue. A value in a manifest
	// would be a promise about a process that may never have started.
	Queue string `protobuf:"bytes,5,opt,name=queue,proto3" json:"queue,omitempty"`
	// THE FILE NO LONGER IMPORTS — a broken workflow is a STATE, not a silence. "" = it imports.
	//
	// A watch-mode serve (`kontra workflow serve --watch`) re-derives this descriptor on every save,
	// by importing the file the same way the worker did on boot. When that import raises — a syntax
	// error, a missing name, a bad annotation — there is no schema to derive and the honest answer is
	// not the last good form left standing as though nothing happened, which reads as "your code is
	// fine" over a file that will not load. It is this: what the import said, verbatim, keyed by the
	// type the manifest declares. The Workflows page draws it on the contract panel, so the loop
	// doubles as a liveness check on the operator's own code. Recovering re-derives a clean descriptor
	// that clears it — the panel restores the form without the serve being restarted.
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDescriptor) Reset() {
	*x = WorkflowDescriptor{}
	mi := &file_kontra_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDescriptor) ProtoMessage() {}

func (x *WorkflowDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_kontra_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDescriptor.ProtoReflect.Descriptor instead.
func (*WorkflowDescriptor) Descriptor() ([]byte, []int) {
	return file_kontra_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowDescriptor) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *WorkflowDescriptor) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *WorkflowDescriptor) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *WorkflowDescriptor) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_kontra_v1_catalog_proto protoreflect.FileDescriptor

const file_kontra_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x17kontra/v1/catalog.proto\x12\tkontra.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe3\x01\n" +
	"\x0fActorDescriptor\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"operations\x18\x05 \x03(\v2\x19.kontra.v1.ActorOperationR\n" +
	"operations\x12\x16\n" +
	"\x06digest\x18\x06 \x01(\tR\x06digest\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"\xe5\x01\n" +
	"\x0eActorOperation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\x12/\n" +
	"\x06output\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06output\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescriptionJ\x04\b\x06\x10\aR\x06stream\"\xd6\x01\n" +
	"\x12WorkflowDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\x12/\n" +
	"\x06output\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x14\n" +
	"\x05queue\x18\x05 \x01(\tR\x05queue\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05errorBIZGgithub.com/medmahmoudi26/kontra/runtime/handler/_gen/kontra/v1;kontrav1b\x06proto3"

var (
	file_kontra_v1_catalog_proto_rawDescOnce sync.Once
	file_kontra_v1_catalog_proto_rawDescData []byte
)

func file_kontra_v1_catalog_proto_rawDescGZIP() []byte {
	file_kontra_v1_catalog_proto_rawDescOnce.Do(func() {
		file_kontra_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kontra_v1_catalog_proto_rawDesc), len(file_kontra_v1_catalog_proto_rawDesc)))
	})
	return file_kontra_v1_catalog_proto_rawDescData
}

var file_kontra_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kontra_v1_catalog_proto_goTypes = []any{
	(*ActorDescriptor)(nil),    // 0: kontra.v1.ActorDescriptor
	(*ActorOperation)(nil),     // 1: kontra.v1.ActorOperation
	(*WorkflowDescriptor)(nil), // 2: kontra.v1.WorkflowDescriptor
	(*structpb.Struct)(nil),    // 3: google.protobuf.Struct
}
var file_kontra_v1_catalog_proto_depIdxs = []int32{
	1, // 0: kontra.v1.ActorDescriptor.operations:type_name -> kontra.v1.ActorOperation
	3, // 1: kontra.v1.ActorOperation.params:type_name -> google.protobuf.Struct
	3, // 2: kontra.v1.ActorOperation.input:type_name -> google.protobuf.Struct
	3, // 3: kontra.v1.ActorOperation.output:type_name -> google.protobuf.Struct
	3, // 4: kontra.v1.WorkflowDescriptor.input:type_name -> google.protobuf.Struct
	3, // 5: kontra.v1.WorkflowDescriptor.output:type_name -> google.protobuf.Struct
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_kontra_v1_catalog_proto_init() }
func file_kontra_v1_catalog_proto_init() {
	if File_kontra_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kontra_v1_catalog_proto_rawDesc), len(file_kontra_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kontra_v1_catalog_proto_goTypes,
		DependencyIndexes: file_kontra_v1_catalog_proto_depIdxs,
		MessageInfos:      file_kontra_v1_catalog_proto_msgTypes,
	}.Build()
	File_kontra_v1_catalog_proto = out.File
	file_kontra_v1_catalog_proto_goTypes = nil
	file_kontra_v1_catalog_proto_depIdxs = nil
}
