// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: temporal/api/enums/v1/reset.proto

/* eslint-disable */

export const protobufPackage = "temporal.api.enums.v1";

/** Event types to exclude when reapplying events beyond the reset point. */
export enum ResetReapplyExcludeType {
  RESET_REAPPLY_EXCLUDE_TYPE_UNSPECIFIED = 0,
  /** RESET_REAPPLY_EXCLUDE_TYPE_SIGNAL - Exclude signals when reapplying events beyond the reset point. */
  RESET_REAPPLY_EXCLUDE_TYPE_SIGNAL = 1,
  /** RESET_REAPPLY_EXCLUDE_TYPE_UPDATE - Exclude updates when reapplying events beyond the reset point. */
  RESET_REAPPLY_EXCLUDE_TYPE_UPDATE = 2,
  /** RESET_REAPPLY_EXCLUDE_TYPE_NEXUS - Exclude nexus events when reapplying events beyond the reset point. */
  RESET_REAPPLY_EXCLUDE_TYPE_NEXUS = 3,
  /**
   * RESET_REAPPLY_EXCLUDE_TYPE_CANCEL_REQUEST - Deprecated, unimplemented option.
   *
   * @deprecated
   */
  RESET_REAPPLY_EXCLUDE_TYPE_CANCEL_REQUEST = 4,
  UNRECOGNIZED = -1,
}

/**
 * Deprecated: applications should use ResetReapplyExcludeType to specify
 * exclusions from this set, and new event types should be added to ResetReapplyExcludeType
 * instead of here.
 */
export enum ResetReapplyType {
  RESET_REAPPLY_TYPE_UNSPECIFIED = 0,
  /** RESET_REAPPLY_TYPE_SIGNAL - Signals are reapplied when workflow is reset. */
  RESET_REAPPLY_TYPE_SIGNAL = 1,
  /** RESET_REAPPLY_TYPE_NONE - No events are reapplied when workflow is reset. */
  RESET_REAPPLY_TYPE_NONE = 2,
  /** RESET_REAPPLY_TYPE_ALL_ELIGIBLE - All eligible events are reapplied when workflow is reset. */
  RESET_REAPPLY_TYPE_ALL_ELIGIBLE = 3,
  UNRECOGNIZED = -1,
}

/** Deprecated, see temporal.api.common.v1.ResetOptions. */
export enum ResetType {
  RESET_TYPE_UNSPECIFIED = 0,
  /** RESET_TYPE_FIRST_WORKFLOW_TASK - Resets to event of the first workflow task completed, or if it does not exist, the event after task scheduled. */
  RESET_TYPE_FIRST_WORKFLOW_TASK = 1,
  /** RESET_TYPE_LAST_WORKFLOW_TASK - Resets to event of the last workflow task completed, or if it does not exist, the event after task scheduled. */
  RESET_TYPE_LAST_WORKFLOW_TASK = 2,
  UNRECOGNIZED = -1,
}
