// Code generated by protoc-gen-go_temporal. DO NOT EDIT.
// versions:
//
//	protoc-gen-go_temporal dev (latest)
//	protoc (unknown)
//
// source: kontra/v1/actor_service.proto
package kontrav1temporal

import (
	"context"
	errs "github.com/cludden/protoc-gen-go-temporal/pkg/errs"
	v1 "github.com/medmahmoudi26/kontra-local/handler/_gen/kontra/v1"
	nexus "github.com/nexus-rpc/sdk-go/nexus"
	temporalnexus "go.temporal.io/sdk/temporalnexus"
	worker "go.temporal.io/sdk/worker"
	workflow "go.temporal.io/sdk/workflow"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	"time"
)

// Nexus handler for kontra.v1.ActorService
//
// Deprecated: Use native nexus implementation instead
type ActorServiceNexusHandler struct{}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
func (h *ActorServiceNexusHandler) Run(name string) nexus.Operation[*v1.EntryInput, *v1.BareRef] {
	return temporalnexus.MustNewWorkflowRunOperationWithOptions(temporalnexus.WorkflowRunOperationOptions[*v1.EntryInput, *v1.BareRef]{
		Handler: func(ctx context.Context, input *v1.EntryInput, opts nexus.StartOperationOptions) (temporalnexus.WorkflowHandle[*v1.BareRef], error) {
			o, err := v1.NewRunOptions().Build(input.ProtoReflect())
			if err != nil {
				return nil, nexus.HandlerErrorf(nexus.HandlerErrorTypeBadRequest, "failed to build workflow options: %w", err)
			}
			return temporalnexus.ExecuteUntypedWorkflow[*v1.BareRef](ctx, opts, o, v1.RunWorkflowName, input)
		},
		Name: name,
	})
}

// ActorServiceServiceName defines the fully-qualified ActorService nexus service name
const ActorServiceServiceName = "kontra.actor"

// RegisterActorServiceOperations registers all kontra.v1.ActorService nexus operations with the given service
func RegisterActorServiceOperations(svc *nexus.Service) error {
	return svc.Register(
		RunWorkflowOperation,
	)
}

// RegisterActorServiceNexusService registers a kontra.v1.ActorService nexus service with a given worker
func RegisterActorServiceNexusService(r worker.NexusServiceRegistry) error {
	svc := nexus.NewService(ActorServiceServiceName)
	if err := RegisterActorServiceOperations(svc); err != nil {
		return err
	}
	r.RegisterNexusService(svc)
	return nil
}

// RunWorkflowOperationName defines the fully-qualified name for a kontra.v1.ActorService.Run nexus workflow operation
const RunWorkflowOperationName = "run"

// RunWorkflowOperation defines a(n) kontra.v1.ActorService.Run nexus workflow operation
var RunWorkflowOperation = temporalnexus.MustNewWorkflowRunOperationWithOptions(
	temporalnexus.WorkflowRunOperationOptions[*v1.EntryInput, *v1.BareRef]{
		Name: RunWorkflowOperationName,
		Handler: func(ctx context.Context, input *v1.EntryInput, opts nexus.StartOperationOptions) (temporalnexus.WorkflowHandle[*v1.BareRef], error) {
			o, err := v1.NewRunOptions().Build(input.ProtoReflect())
			if err != nil {
				return nil, nexus.HandlerErrorf(nexus.HandlerErrorTypeBadRequest, "failed to build workflow options: %w", err)
			}
			return temporalnexus.ExecuteUntypedWorkflow[*v1.BareRef](ctx, opts, o, v1.RunWorkflowName, input)
		},
	},
)

// RunWorkflowOperationFuture describes a handle to an asynchronous kontra.v1.ActorService.Run nexus workflow operation
type RunWorkflowOperationFuture interface {
	// Future returns the underlying NexusOperationFuture
	Future() workflow.NexusOperationFuture
	// Get blocks until the nexus operation is complete, returning the result or error
	Get(ctx workflow.Context) (*v1.BareRef, error)
}

// runWorkflowOperationFuture provides an internal RunWorkflowOperationFuture implementation
type runWorkflowOperationFuture struct {
	f workflow.NexusOperationFuture
}

// Future returns the underlying NexusOperationFuture
func (f *runWorkflowOperationFuture) Future() workflow.NexusOperationFuture {
	return f.f
}

// Get blocks until the nexus operation is complete, returning the result or error
func (f *runWorkflowOperationFuture) Get(ctx workflow.Context) (*v1.BareRef, error) {
	var out v1.BareRef
	return &out, f.f.Get(ctx, &out)
}

// RunWorkflowOperationOptions provides methods for configuration a(n) kontra.v1.ActorService.Run nexus workflow operation
type RunWorkflowOperationOptions struct {
	opts                   *workflow.NexusOperationOptions
	scheduleToCloseTimeout *durationpb.Duration
}

// NewRunWorkflowOperationOptions initializes a new RunWorkflowOperationOptions value
func NewRunWorkflowOperationOptions() *RunWorkflowOperationOptions {
	return &RunWorkflowOperationOptions{}
}

// Build converts a(n) RunWorkflowOperationOptions value into a workflow.NexusOperationOptions value
func (o *RunWorkflowOperationOptions) Build(ctx workflow.Context) (workflow.NexusOperationOptions, error) {
	var opts workflow.NexusOperationOptions
	if o == nil {
		return opts, nil
	}

	if v := o.opts; v != nil {
		opts = *o.opts
	}

	if v := o.scheduleToCloseTimeout; v.IsValid() {
		opts.ScheduleToCloseTimeout = v.AsDuration()
	}

	return opts, nil
}

// WithOptions overrides the initial NexusOperationOptions to which defaults and overrides are then applied
func (o *RunWorkflowOperationOptions) WithOptions(opts workflow.NexusOperationOptions) *RunWorkflowOperationOptions {
	o.opts = &opts
	return o
}

// WithScheduleToCloseTimeout overrides the default ScheduleToCloseTimeout
func (o *RunWorkflowOperationOptions) WithScheduleToCloseTimeout(d time.Duration) *RunWorkflowOperationOptions {
	o.scheduleToCloseTimeout = durationpb.New(d)
	return o
}

// ActorServiceNexusClient describes a(n) kontra.v1.ActorService nexus client
type ActorServiceNexusClient interface {
	// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
	Run(ctx workflow.Context, input *v1.EntryInput, options ...*RunWorkflowOperationOptions) (*v1.BareRef, error)
	// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
	RunAsync(ctx workflow.Context, input *v1.EntryInput, options ...*RunWorkflowOperationOptions) RunWorkflowOperationFuture
}

// actorServiceNexusClient provides an internal ActorServiceNexusClient implementation
type actorServiceNexusClient struct {
	client workflow.NexusClient
}

// NewActorServiceNexusClient initializes a new kontra.actor nexus client
func NewActorServiceNexusClient(endpoint string) ActorServiceNexusClient {
	return &actorServiceNexusClient{
		client: workflow.NewNexusClient(endpoint, ActorServiceServiceName),
	}
}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
func (c *actorServiceNexusClient) Run(ctx workflow.Context, input *v1.EntryInput, options ...*RunWorkflowOperationOptions) (*v1.BareRef, error) {
	return c.RunAsync(ctx, input, options...).Get(ctx)
}

// kontra.actor:run — the dispatch op. EntryInput in, BareRef out (return_ref path).
func (c *actorServiceNexusClient) RunAsync(ctx workflow.Context, input *v1.EntryInput, options ...*RunWorkflowOperationOptions) RunWorkflowOperationFuture {
	var o *RunWorkflowOperationOptions
	if len(options) > 0 && options[0] != nil {
		o = options[0]
	}

	opts, err := o.Build(ctx)
	if err != nil {
		return &runWorkflowOperationFuture{
			f: errs.NewNexusOperationFutureError(err),
		}
	}

	return &runWorkflowOperationFuture{
		f: c.client.ExecuteOperation(ctx, RunWorkflowOperationName, input, opts),
	}
}
