// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: temporal/api/common/v1/message.proto

/* eslint-disable */
import { type Duration } from "../../../../google/protobuf/duration";
import { type Empty } from "../../../../google/protobuf/empty";
import { type EncodingType } from "../../enums/v1/common";
import { type EventType } from "../../enums/v1/event_type";
import { type ResetReapplyExcludeType, type ResetReapplyType } from "../../enums/v1/reset";

export const protobufPackage = "temporal.api.common.v1";

export interface DataBlob {
  encoding_type: EncodingType;
  data: Uint8Array;
}

/** See `Payload` */
export interface Payloads {
  payloads: Payload[];
}

/**
 * Represents some binary (byte array) data (ex: activity input parameters or workflow result) with
 * metadata which describes this binary data (format, encoding, encryption, etc). Serialization
 * of the data may be user-defined.
 */
export interface Payload {
  metadata: { [key: string]: Uint8Array };
  data: Uint8Array;
  /** Details about externally stored payloads associated with this payload. */
  external_payloads: Payload_ExternalPayloadDetails[];
}

export interface Payload_MetadataEntry {
  key: string;
  value: Uint8Array;
}

/** Describes an externally stored object referenced by this payload. */
export interface Payload_ExternalPayloadDetails {
  /** Size in bytes of the externally stored payload */
  size_bytes: number;
}

/**
 * A user-defined set of *indexed* fields that are used/exposed when listing/searching workflows.
 * The payload is not serialized in a user-defined way.
 */
export interface SearchAttributes {
  indexed_fields: { [key: string]: Payload };
}

export interface SearchAttributes_IndexedFieldsEntry {
  key: string;
  value: Payload | undefined;
}

/** A user-defined set of *unindexed* fields that are exposed when listing/searching workflows */
export interface Memo {
  fields: { [key: string]: Payload };
}

export interface Memo_FieldsEntry {
  key: string;
  value: Payload | undefined;
}

/**
 * Contains metadata that can be attached to a variety of requests, like starting a workflow, and
 * can be propagated between, for example, workflows and activities.
 */
export interface Header {
  fields: { [key: string]: Payload };
}

export interface Header_FieldsEntry {
  key: string;
  value: Payload | undefined;
}

/**
 * Identifies a specific workflow within a namespace. Practically speaking, because run_id is a
 * uuid, a workflow execution is globally unique. Note that many commands allow specifying an empty
 * run id as a way of saying "target the latest run of the workflow".
 */
export interface WorkflowExecution {
  workflow_id: string;
  run_id: string;
}

/**
 * Represents the identifier used by a workflow author to define the workflow. Typically, the
 * name of a function. This is sometimes referred to as the workflow's "name"
 */
export interface WorkflowType {
  name: string;
}

/**
 * Represents the identifier used by a activity author to define the activity. Typically, the
 * name of a function. This is sometimes referred to as the activity's "name"
 */
export interface ActivityType {
  name: string;
}

/** How retries ought to be handled, usable by both workflows and activities */
export interface RetryPolicy {
  /** Interval of the first retry. If retryBackoffCoefficient is 1.0 then it is used for all retries. */
  initial_interval:
    | Duration
    | undefined;
  /**
   * Coefficient used to calculate the next retry interval.
   * The next retry interval is previous interval multiplied by the coefficient.
   * Must be 1 or larger.
   */
  backoff_coefficient: number;
  /**
   * Maximum interval between retries. Exponential backoff leads to interval increase.
   * This value is the cap of the increase. Default is 100x of the initial interval.
   */
  maximum_interval:
    | Duration
    | undefined;
  /**
   * Maximum number of attempts. When exceeded the retries stop even if not expired yet.
   * 1 disables retries. 0 means unlimited (up to the timeouts)
   */
  maximum_attempts: number;
  /**
   * Non-Retryable errors types. Will stop retrying if the error type matches this list. Note that
   * this is not a substring match, the error *type* (not message) must match exactly.
   */
  non_retryable_error_types: string[];
}

/** Metadata relevant for metering purposes */
export interface MeteringMetadata {
  /**
   * Count of local activities which have begun an execution attempt during this workflow task,
   * and whose first attempt occurred in some previous task. This is used for metering
   * purposes, and does not affect workflow state.
   *
   * (-- api-linter: core::0141::forbidden-types=disabled
   *     aip.dev/not-precedent: Negative values make no sense to represent. --)
   */
  nonfirst_local_activity_execution_attempts: number;
}

/**
 * Deprecated. This message is replaced with `Deployment` and `VersioningBehavior`.
 * Identifies the version(s) of a worker that processed a task
 */
export interface WorkerVersionStamp {
  /**
   * An opaque whole-worker identifier. Replaces the deprecated `binary_checksum` field when this
   * message is included in requests which previously used that.
   */
  build_id: string;
  /**
   * If set, the worker is opting in to worker versioning. Otherwise, this is used only as a
   * marker for workflow reset points and the BuildIDs search attribute.
   */
  use_versioning: boolean;
}

/**
 * Identifies the version that a worker is compatible with when polling or identifying itself,
 * and whether or not this worker is opting into the build-id based versioning feature. This is
 * used by matching to determine which workers ought to receive what tasks.
 * Deprecated. Use WorkerDeploymentOptions instead.
 */
export interface WorkerVersionCapabilities {
  /** An opaque whole-worker identifier */
  build_id: string;
  /**
   * If set, the worker is opting in to worker versioning, and wishes to only receive appropriate
   * tasks.
   */
  use_versioning: boolean;
  /** Must be sent if user has set a deployment series name (versioning-3). */
  deployment_series_name: string;
}

/**
 * Describes where and how to reset a workflow, used for batch reset currently
 * and may be used for single-workflow reset later.
 */
export interface ResetOptions {
  /** Resets to the first workflow task completed or started event. */
  first_workflow_task?:
    | Empty
    | undefined;
  /** Resets to the last workflow task completed or started event. */
  last_workflow_task?:
    | Empty
    | undefined;
  /**
   * The id of a specific `WORKFLOW_TASK_COMPLETED`,`WORKFLOW_TASK_TIMED_OUT`, `WORKFLOW_TASK_FAILED`, or
   * `WORKFLOW_TASK_STARTED` event to reset to.
   * Note that this option doesn't make sense when used as part of a batch request.
   */
  workflow_task_id?:
    | number
    | undefined;
  /**
   * Resets to the first workflow task processed by this build id.
   * If the workflow was not processed by the build id, or the workflow task can't be
   * determined, no reset will be performed.
   * Note that by default, this reset is allowed to be to a prior run in a chain of
   * continue-as-new.
   */
  build_id?:
    | string
    | undefined;
  /**
   * Deprecated. Use `options`.
   * Default: RESET_REAPPLY_TYPE_SIGNAL
   *
   * @deprecated
   */
  reset_reapply_type: ResetReapplyType;
  /**
   * If true, limit the reset to only within the current run. (Applies to build_id targets and
   * possibly others in the future.)
   */
  current_run_only: boolean;
  /** Event types not to be reapplied */
  reset_reapply_exclude_types: ResetReapplyExcludeType[];
}

/** Callback to attach to various events in the system, e.g. workflow run completion. */
export interface Callback {
  nexus?: Callback_Nexus | undefined;
  internal?:
    | Callback_Internal
    | undefined;
  /**
   * Links associated with the callback. It can be used to link to underlying resources of the
   * callback.
   */
  links: Link[];
}

export interface Callback_Nexus {
  /** Callback URL. */
  url: string;
  /** Header to attach to callback request. */
  header: { [key: string]: string };
}

export interface Callback_Nexus_HeaderEntry {
  key: string;
  value: string;
}

/**
 * Callbacks to be delivered internally within the system.
 * This variant is not settable in the API and will be rejected by the service with an INVALID_ARGUMENT error.
 * The only reason that this is exposed is because callbacks are replicated across clusters via the
 * WorkflowExecutionStarted event, which is defined in the public API.
 */
export interface Callback_Internal {
  /** Opaque internal data. */
  data: Uint8Array;
}

/**
 * Link can be associated with history events. It might contain information about an external entity
 * related to the history event. For example, workflow A makes a Nexus call that starts workflow B:
 * in this case, a history event in workflow A could contain a Link to the workflow started event in
 * workflow B, and vice-versa.
 */
export interface Link {
  workflow_event?: Link_WorkflowEvent | undefined;
  batch_job?: Link_BatchJob | undefined;
}

export interface Link_WorkflowEvent {
  namespace: string;
  workflow_id: string;
  run_id: string;
  event_ref?: Link_WorkflowEvent_EventReference | undefined;
  request_id_ref?: Link_WorkflowEvent_RequestIdReference | undefined;
}

/** EventReference is a direct reference to a history event through the event ID. */
export interface Link_WorkflowEvent_EventReference {
  event_id: number;
  event_type: EventType;
}

/** RequestIdReference is a indirect reference to a history event through the request ID. */
export interface Link_WorkflowEvent_RequestIdReference {
  request_id: string;
  event_type: EventType;
}

/**
 * A link to a built-in batch job.
 * Batch jobs can be used to perform operations on a set of workflows (e.g. terminate, signal, cancel, etc).
 * This link can be put on workflow history events generated by actions taken by a batch job.
 */
export interface Link_BatchJob {
  job_id: string;
}

/**
 * Priority contains metadata that controls relative ordering of task processing
 * when tasks are backed up in a queue. Initially, Priority will be used in
 * matching (workflow and activity) task queues. Later it may be used in history
 * task queues and in rate limiting decisions.
 *
 * Priority is attached to workflows and activities. By default, activities
 * inherit Priority from the workflow that created them, but may override fields
 * when an activity is started or modified.
 *
 * Despite being named "Priority", this message also contains fields that
 * control "fairness" mechanisms.
 *
 * For all fields, the field not present or equal to zero/empty string means to
 * inherit the value from the calling workflow, or if there is no calling
 * workflow, then use the default value.
 *
 * For all fields other than fairness_key, the zero value isn't meaningful so
 * there's no confusion between inherit/default and a meaningful value. For
 * fairness_key, the empty string will be interpreted as "inherit". This means
 * that if a workflow has a non-empty fairness key, you can't override the
 * fairness key of its activity to the empty string.
 *
 * The overall semantics of Priority are:
 * 1. First, consider "priority": higher priority (lower number) goes first.
 * 2. Then, consider fairness: try to dispatch tasks for different fairness keys
 *    in proportion to their weight.
 *
 * Applications may use any subset of mechanisms that are useful to them and
 * leave the other fields to use default values.
 *
 * Not all queues in the system may support the "full" semantics of all priority
 * fields. (Currently only support in matching task queues is planned.)
 */
export interface Priority {
  /**
   * Priority key is a positive integer from 1 to n, where smaller integers
   * correspond to higher priorities (tasks run sooner). In general, tasks in
   * a queue should be processed in close to priority order, although small
   * deviations are possible.
   *
   * The maximum priority value (minimum priority) is determined by server
   * configuration, and defaults to 5.
   *
   * If priority is not present (or zero), then the effective priority will be
   * the default priority, which is calculated by (min+max)/2. With the
   * default max of 5, and min of 1, that comes out to 3.
   */
  priority_key: number;
  /**
   * Fairness key is a short string that's used as a key for a fairness
   * balancing mechanism. It may correspond to a tenant id, or to a fixed
   * string like "high" or "low". The default is the empty string.
   *
   * The fairness mechanism attempts to dispatch tasks for a given key in
   * proportion to its weight. For example, using a thousand distinct tenant
   * ids, each with a weight of 1.0 (the default) will result in each tenant
   * getting a roughly equal share of task dispatch throughput.
   *
   * (Note: this does not imply equal share of worker capacity! Fairness
   * decisions are made based on queue statistics, not
   * current worker load.)
   *
   * As another example, using keys "high" and "low" with weight 9.0 and 1.0
   * respectively will prefer dispatching "high" tasks over "low" tasks at a
   * 9:1 ratio, while allowing either key to use all worker capacity if the
   * other is not present.
   *
   * All fairness mechanisms, including rate limits, are best-effort and
   * probabilistic. The results may not match what a "perfect" algorithm with
   * infinite resources would produce. The more unique keys are used, the less
   * accurate the results will be.
   *
   * Fairness keys are limited to 64 bytes.
   */
  fairness_key: string;
  /**
   * Fairness weight for a task can come from multiple sources for
   * flexibility. From highest to lowest precedence:
   * 1. Weights for a small set of keys can be overridden in task queue
   *    configuration with an API.
   * 2. It can be attached to the workflow/activity in this field.
   * 3. The default weight of 1.0 will be used.
   *
   * Weight values are clamped to the range [0.001, 1000].
   */
  fairness_weight: number;
}

/**
 * This is used to send commands to a specific worker or a group of workers.
 * Right now, it is used to send commands to a specific worker instance.
 * Will be extended to be able to send command to multiple workers.
 */
export interface WorkerSelector {
  /** Worker instance key to which the command should be sent. */
  worker_instance_key?: string | undefined;
}
