# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kontra/v1/actor.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'kontra/v1/actor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from kontra.v1 import entry_pb2 as kontra_dot_v1_dot_entry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15kontra/v1/actor.proto\x12\tkontra.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15kontra/v1/entry.proto\"\xbf\x02\n\rActorRunInput\x12,\n\x05units\x18\x01 \x03(\x0b\x32\x16.google.protobuf.ValueR\x05units\x12/\n\tunits_ref\x18\x02 \x01(\x0b\x32\x12.kontra.v1.BareRefR\x08unitsRef\x12/\n\x06params\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructR\x06params\x12\x15\n\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x16\n\x06tenant\x18\x05 \x01(\tR\x06tenant\x12\'\n\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12\'\n\x0f\x65xpected_digest\x18\x07 \x01(\tR\x0e\x65xpectedDigest\x12\x1d\n\nreturn_ref\x18\x08 \x01(\x08R\treturnRef\"\xac\x01\n\x0e\x41\x63torRunResult\x12\x30\n\x07results\x18\x01 \x03(\x0b\x32\x16.google.protobuf.ValueR\x07results\x12\x35\n\x08\x66\x61ilures\x18\x02 \x03(\x0b\x32\x19.kontra.v1.PerUnitFailureR\x08\x66\x61ilures\x12\x31\n\nresult_ref\x18\x03 \x01(\x0b\x32\x12.kontra.v1.BareRefR\tresultRef\"\x84\x01\n\x0ePerUnitFailure\x12*\n\x04unit\x18\x01 \x01(\x0b\x32\x16.google.protobuf.ValueR\x04unit\x12*\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.kontra.v1.ErrorInfoR\x05\x65rror\x12\x1a\n\x08\x63\x61tegory\x18\x03 \x01(\tR\x08\x63\x61tegory\"9\n\tErrorInfo\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n\x07message\x18\x02 \x01(\tR\x07messageBIZGgithub.com/medmahmoudi26/kontra/runtime/handler/_gen/kontra/v1;kontrav1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kontra.v1.actor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGgithub.com/medmahmoudi26/kontra/runtime/handler/_gen/kontra/v1;kontrav1'
  _globals['_ACTORRUNINPUT']._serialized_start=90
  _globals['_ACTORRUNINPUT']._serialized_end=409
  _globals['_ACTORRUNRESULT']._serialized_start=412
  _globals['_ACTORRUNRESULT']._serialized_end=584
  _globals['_PERUNITFAILURE']._serialized_start=587
  _globals['_PERUNITFAILURE']._serialized_end=719
  _globals['_ERRORINFO']._serialized_start=721
  _globals['_ERRORINFO']._serialized_end=778
# @@protoc_insertion_point(module_scope)
