# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kontra/v1/actor_service.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'kontra/v1/actor_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporal.v1 import temporal_pb2 as temporal_dot_v1_dot_temporal__pb2
from kontra.v1 import entry_pb2 as kontra_dot_v1_dot_entry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dkontra/v1/actor_service.proto\x12\tkontra.v1\x1a\x1atemporal/v1/temporal.proto\x1a\x15kontra/v1/entry.proto2\xa4\x01\n\x0c\x41\x63torService\x12n\n\x03Run\x12\x15.kontra.v1.EntryInput\x1a\x12.kontra.v1.BareRef\"<\x8a\xc4\x03\x38*.actor-${!idempotency_key.or(run_id).or(\"run\")}\xc2\x01\x05\x12\x03run\x1a$\x8a\xc4\x03 \n\x0ckontra-actor\"\x10\x08\x01\x12\x0ckontra.actorBGZEgithub.com/medmahmoudi26/kontra-local/handler/_gen/kontra/v1;kontrav1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kontra.v1.actor_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZEgithub.com/medmahmoudi26/kontra-local/handler/_gen/kontra/v1;kontrav1'
  _globals['_ACTORSERVICE']._loaded_options = None
  _globals['_ACTORSERVICE']._serialized_options = b'\212\304\003 \n\014kontra-actor\"\020\010\001\022\014kontra.actor'
  _globals['_ACTORSERVICE'].methods_by_name['Run']._loaded_options = None
  _globals['_ACTORSERVICE'].methods_by_name['Run']._serialized_options = b'\212\304\0038*.actor-${!idempotency_key.or(run_id).or(\"run\")}\302\001\005\022\003run'
  _globals['_ACTORSERVICE']._serialized_start=96
  _globals['_ACTORSERVICE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
