# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kontra/v1/entry.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'kontra/v1/entry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15kontra/v1/entry.proto\x12\tkontra.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa0\x01\n\x07\x42\x61reRef\x12\x16\n\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n\x04size\x18\x02 \x01(\x04R\x04size\x12\x30\n\x04meta\x18\x03 \x03(\x0b\x32\x1c.kontra.v1.BareRef.MetaEntryR\x04meta\x1a\x37\n\tMetaEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xbf\x03\n\nEntryInput\x12,\n\x05units\x18\x01 \x03(\x0b\x32\x16.google.protobuf.ValueR\x05units\x12/\n\tinput_ref\x18\x02 \x01(\x0b\x32\x12.kontra.v1.BareRefR\x08inputRef\x12\x1d\n\nreturn_ref\x18\x06 \x01(\x08R\treturnRef\x12\x15\n\x06run_id\x18\x07 \x01(\tR\x05runId\x12\'\n\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12\x17\n\x07node_id\x18\x0c \x01(\tR\x06nodeId\x12\'\n\x0f\x65xpected_digest\x18\n \x01(\tR\x0e\x65xpectedDigest\x12/\n\x06params\x18\x0b \x01(\x0b\x32\x17.google.protobuf.StructR\x06params\x12\x16\n\x06method\x18\r \x01(\tR\x06method\x12\x1d\n\nsession_id\x18\x0e \x01(\tR\tsessionIdJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x08\x10\tR\noutput_uriR\x11parallel_sessionsR\nchunk_sizeR\x06tenantBAZ?github.com/medmahmoudi26/kontra/handler/_gen/kontra/v1;kontrav1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kontra.v1.entry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/medmahmoudi26/kontra/handler/_gen/kontra/v1;kontrav1'
  _globals['_BAREREF_METAENTRY']._loaded_options = None
  _globals['_BAREREF_METAENTRY']._serialized_options = b'8\001'
  _globals['_BAREREF']._serialized_start=67
  _globals['_BAREREF']._serialized_end=227
  _globals['_BAREREF_METAENTRY']._serialized_start=172
  _globals['_BAREREF_METAENTRY']._serialized_end=227
  _globals['_ENTRYINPUT']._serialized_start=230
  _globals['_ENTRYINPUT']._serialized_end=677
# @@protoc_insertion_point(module_scope)
