// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: kontra/v1/actor.proto

/* eslint-disable */
import { type BareRef } from "./entry";

export const protobufPackage = "kontra.v1";

/** Input to an actor over ONE batch — the single argument to the ActorWorkflow. */
export interface ActorRunInput {
  /**
   * This batch's units, inline (the CLI/DIY path). Exactly one of units / units_ref
   * carries the batch.
   */
  units: any[];
  /** OR the batch as a CAS ref the actor materializes (refs-as-currency, ADR 0007). */
  units_ref:
    | BareRef
    | undefined;
  /** Run-wide config -> the author's self.params. NON-secret (params ride history). */
  params:
    | { [key: string]: any }
    | undefined;
  /**
   * Lineage the dispatcher stamps (ADR 0006); surfaced to the author as self.run_id /
   * self.idempotency_key. tenant is dispatcher bookkeeping. "" = unset (CLI/DIY path).
   */
  run_id: string;
  tenant: string;
  idempotency_key: string;
  /**
   * Content-pinned identity (ADR 0011): the OCI image digest this run was designed
   * against. The worker self-verifies its running digest and fails fast (non-retryable,
   * ActorDigestDrift) on drift. "" = unpinned (enforcement off).
   */
  expected_digest: string;
  /**
   * When true the actor returns a BareRef (result_ref) instead of inline results, so the
   * dispatcher stays ref-only.
   */
  return_ref: boolean;
}

/**
 * The result of running an actor over one batch: the {results, failures} envelope, inline
 * or as a CAS ref. Formalizes the envelope that today lives only in each SDK (Python
 * dataclass / TS type / Go struct), never in proto.
 */
export interface ActorRunResult {
  /** The arun's output units. Empty when result_ref is set. */
  results: any[];
  /** Per-unit failures isolated within this run (the durability surface). */
  failures: PerUnitFailure[];
  /** Set when ActorRunInput.return_ref: the {results, failures} envelope content-addressed. */
  result_ref: BareRef | undefined;
}

/** One isolated unit failure. The full unit is the correlation key (no positional index). */
export interface PerUnitFailure {
  unit: any | undefined;
  error:
    | ErrorInfo
    | undefined;
  /**
   * "terminal"  — non-retryable: isolated on the first attempt (author NonRetryable, a
   *               non_retryable_errors match, or ActorDigestDrift/SessionUnrecoverable).
   * "exhausted" — retryable: isolated after the activity's retry policy ran out.
   */
  category: string;
}

export interface ErrorInfo {
  /**
   * The cross-language error-type name (e.g. SessionLost, ActorDigestDrift, the author's
   * NonRetryable subclass name) — matched against the activity's non-retryable error types.
   */
  type: string;
  message: string;
}
