// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: kontra/v1/catalog.proto

/* eslint-disable */

export const protobufPackage = "kontra.v1";

/**
 * The cross-language ACTOR DESCRIPTOR — the `describe()` output every language SDK
 * emits and the orchestrator catalog stores via POST /api/actors. This is the
 * discovery contract: a (name, version) actor becomes visible to the graph editor and
 * `pnpm dispatch` once its descriptor is registered.
 *
 * Per-actor I/O is JSON Schema (Draft 2020-12), NOT proto, so the operation schemas are
 * opaque google.protobuf.Struct and not typed messages. The descriptor carries identity +
 * the per-operation schemas only; it does not model what is inside them.
 *
 * NOTHING OUTSIDE THIS REPO OWNS THAT COMPATIBILITY. This header used to name an external
 * schema registry (ADR 0008) as the owner of I/O compat, and no such service existed: none in
 * docker-compose, no client, nothing calling one. A contract file asserting a component that
 * does not exist is worse than silence, because it is the place a reader goes to find out who
 * checks. Enforcement is in-process, where the schemas already are — ajv on the execution path
 * (ADR 0003) and the immutability rule at registration (ADR 0004: a version is immutable, any
 * I/O schema change bumps it). ADR 0027 deleted the registry and records what is genuinely
 * lost with it: nothing compares one version's schema to the next.
 *
 * As with entry.proto, this is the shared TYPE DEFINITION the seams are checked against;
 * the wire stays JSON (ADR 0002). Each SDK hand-emits that JSON — Go in
 * runtime/go/registrar, Python in runtime/python/internals/catalog.py — and the
 * orchestrator reads it in POST /api/actors and persists it as ActorRecord
 * (control/orchestrator/src/db/repo.ts). Nothing makes those three agree except one check per side,
 * each written where that side lives and sharing no code with the others:
 * runtime/handler/internal/wire/wire_congruence_test.go reads the generated descriptor back through
 * protoreflect, tests/test_method_types.py holds the posted Python body to it, and
 * control/orchestrator/catalog.contract.ts makes a field this file defines and the store cannot hold
 * a compile error.
 *
 * THOSE THREE CHECK EACH SIDE AGAINST THIS FILE, WHICH IS NOT THE SAME AS THE SIDES AGREEING.
 * `source` was congruent with this file, present in the `actors` table and emitted by Python,
 * and simply absent from the Go emitter — every check above stayed green while a catalogued Go
 * actor had no way back to its code. What holds the emitters to EACH OTHER is one golden
 * descriptor, shared/conformance/catalog.json, that all three compare their real emission to:
 * runtime/go/registrar/conformance_test.go, tests/test_catalog_conformance.py and
 * control/orchestrator/src/catalog.conformance.test.ts.
 */
export interface ActorDescriptor {
  /** "{name}@{version}" — the catalog primary key */
  key: string;
  name: string;
  /** immutable; bump on any I/O schema change (ADR 0004) */
  version: string;
  /** "kontra.actor.v1" */
  schema_version: string;
  operations: ActorOperation[];
  /** OCI image digest the worker self-registers (ADR 0011); "" = unset/dev. */
  digest: string;
  /**
   * The directory the WORKER loaded this actor from; "" = nothing said where.
   *
   * Nothing linked a registered actor back to its code. `.kontra/actors/` is where an
   * operator's own actors go and is usually empty — the catalogued ones were run from
   * `examples/` or a checkout somewhere — so the Actors page could list twenty-three actors
   * and offer no way to reach any of them. It is the path AS THE WORKER SAW IT, which on a
   * fleet Machine is `/opt/kontra/actor/<name>` and not a path on the reader's disk; that is
   * still the honest answer to where the actor came from.
   */
  source: string;
  /**
   * What the image was BUILT ON, and it does not come from the same place the rest of this does.
   *
   * Every other field here is something the worker knows about itself. These two are facts about a
   * BUILD: the run image a buildpack layered onto and the builder that did the layering, neither of
   * which is visible from inside the running container. The deploying CLI records them, the Warden
   * hands them back as environment at container start, and the registrar echoes them — so a worker
   * re-registering does not erase what it cannot independently discover.
   *
   * Absent, not empty, when unknown: the catalog keeps a previous value only when the key is missing
   * (`body.runtime ?? prev.runtime`), so a worker started without them must omit them or every
   * restart would unpin the runtime an image was built on.
   */
  runtime:
    | ActorRuntime
    | undefined;
  /** the CNB builder's digest; json_name is `builderDigest` */
  builder_digest: string;
}

/**
 * The run image an Actor image was layered onto — a Runtime, by name and MAJOR, pinned by digest.
 *
 * The major is what an author declares (`python-browser:1`) and the digest is what the build
 * resolved it to. Both are kept because they answer different questions: the major says which
 * runtime an actor asked for, and the digest says whether it is still on the current one — which is
 * the whole of rebase detection.
 */
export interface ActorRuntime {
  name: string;
  major: number;
  digest: string;
}

/**
 * One operation an actor exposes — ONE PER METHOD (ADR 0023 §9).
 *
 * It used to be exactly one, named "run", because an Actor had exactly one entry point. An
 * Actor now declares as many Methods as it has jobs and each carries its OWN signature:
 * `fetch` takes a URL and emits a page while `title` takes a page, so a single Actor-level
 * pair could only ever describe one of them. `name` is the Method name a caller dispatches.
 *
 * `params` stays ACTOR-level (run-wide config, not a signature) and rides on every operation.
 *
 * input/output are JSON Schema docs (Draft 2020-12), DERIVED from the types a Method declares
 * with `takes=`/`emits=` — which are the same types the author's body reads and writes
 * (`unit.value` is an instance of `takes`, `unit.emit(Emits(...))`). Unset for a Method that
 * declares neither: it still registers and stays dispatchable by name, it simply advertises
 * nothing.
 */
export interface ActorOperation {
  /** the Method's dispatch name */
  name: string;
  /** run-wide config schema, or unset */
  params:
    | { [key: string]: any }
    | undefined;
  /** per-record input schema, or unset */
  input:
    | { [key: string]: any }
    | undefined;
  /** per-record output schema, or unset */
  output:
    | { [key: string]: any }
    | undefined;
  /**
   * What the Method is FOR, in the author's own words — a Go `Does("…")`, the first paragraph
   * of a Python docstring. A catalog of a name and two schemas can say what a Method TAKES and
   * never what it DOES, which leaves an operator composing one Actor's Method into another's
   * with nothing to compose from. "" = the author wrote none; both SDKs omit the JSON key
   * rather than sending an empty string, because undescribed and described-with-nothing render
   * differently and only one of them is actionable.
   *
   * Appended (5), declared last: field numbers here are APPEND-ONLY. Renumbering to put this
   * next to `name` would silently re-point every already-registered descriptor's fields.
   */
  description: string;
}

/**
 * A CALLER WORKFLOW, described — the other half of a run, which today describes nothing.
 *
 * A Run is one execution of a caller's workflow (ADR 0023 §12): the workflow dispatches the
 * actors, and the actors are the only side with a descriptor. `GET /api/workflows` lists
 * `.kontra/workflows/*.py` by filename, byte count and mtime, so every surface that shows a
 * workflow can say that a file exists and nothing about what it accepts, what it returns or
 * what it is for — all three of which are already written down in the source, in the
 * `@workflow.run` signature and the class docstring, and none of which survive to a reader.
 *
 * THE TYPE EXISTS BEFORE THE REGISTRATION PATH, deliberately. Nothing emits one yet. A shape
 * invented in the same commit as the code that fills it is a shape nothing was checked
 * against; this way the emitter has something to be wrong about.
 *
 * Same stance on schemas as ActorOperation: input/output are opaque JSON Schema (Draft
 * 2020-12) documents derived from the types the run method declares, not proto messages.
 */
export interface WorkflowDescriptor {
  /**
   * The workflow TYPE a caller starts — the `@workflow.defn` class name (`Ping`), which is
   * what `kontra workflow start` names and NOT the file it lives in. Two workflows can share
   * a file; the type is what Temporal routes on.
   */
  name: string;
  /** What it is for, from the class docstring's first paragraph; "" = undescribed. */
  description: string;
  /** schema of the run argument, or unset */
  input:
    | { [key: string]: any }
    | undefined;
  /** schema of the return value, or unset */
  output:
    | { [key: string]: any }
    | undefined;
  /**
   * The task queue the registering worker is polling. "" = it did not say.
   *
   * THE OTHER HALF OF "HOW DO I START THIS". `name` is what Temporal routes ON; this is where it
   * routes TO. A start is accepted for any queue name and only a worker polling that exact one
   * takes the task, so the right type on the wrong queue is a run that starts, never progresses,
   * and reports `running` the whole time — or fails its workflow task against a worker that polls
   * that queue and does not know the type. Neither is visible as a wrong queue.
   *
   * The WORKER is the only honest source: it is about to poll this queue. A value in a manifest
   * would be a promise about a process that may never have started.
   */
  queue: string;
  /**
   * THE FILE NO LONGER IMPORTS — a broken workflow is a STATE, not a silence. "" = it imports.
   *
   * A watch-mode serve (`kontra workflow serve --watch`) re-derives this descriptor on every save,
   * by importing the file the same way the worker did on boot. When that import raises — a syntax
   * error, a missing name, a bad annotation — there is no schema to derive and the honest answer is
   * not the last good form left standing as though nothing happened, which reads as "your code is
   * fine" over a file that will not load. It is this: what the import said, verbatim, keyed by the
   * type the manifest declares. The Workflows page draws it on the contract panel, so the loop
   * doubles as a liveness check on the operator's own code. Recovering re-derives a clean descriptor
   * that clears it — the panel restores the form without the serve being restarted.
   */
  error: string;
}
