// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: kontra/v1/run.proto

/* eslint-disable */

export const protobufPackage = "kontra.v1";

export interface RunEnvelope {
  /**
   * Identity / routing. version is IMMUTABLE — a schema change MUST bump it, and
   * build refuses to overwrite an existing (name, version) (ADR 0004, content-
   * pinned identity). Resolves the {name}-{version} queue / Nexus endpoint.
   */
  actor:
    | Actor
    | undefined;
  /**
   * Lineage. run_id is SERVER-MINTED, immutable, and UNIQUE PER EXECUTION — minted
   * at POST /api/runs, never accepted from the client, and distinct from the user-
   * facing graph label (ADR 0006). It is the lineage key threaded into child
   * workflow ids, codec provenance, and the future Iceberg partition columns.
   */
  run_id: string;
  /** which graph node produced this dispatch */
  node_id: string;
  /**
   * Tenancy. Selects the Temporal namespace (namespace-per-author in prod) and
   * scopes the CAS key. Tenant-free today (cas/<sha[:2]>/<sha>); becomes
   * cas/{tenant}/<sha[:2]>/<sha> under namespace-per-author. Present NOW as
   * "default" so adding real tenants later needs no history migration (ADR 0001).
   */
  tenant: string;
  /**
   * Idempotency. A stable (run_id, node_id, generation, unit-index) tuple the SDK
   * exposes to the author as self.idempotency_key, so at-least-once retries and the
   * Iceberg append dedup instead of double-firing side effects.
   */
  idempotency_key: string;
  /**
   * The batch payload: OPAQUE. JSON-encoded units, or a claim-check ref the codec
   * rehydrates transparently. The proto never sees per-actor shape.
   */
  payload: Uint8Array;
  /**
   * Run-wide config (the params block), JSON-encoded, validated against the params
   * JSON Schema. NON-SECRET only — secrets travel as a {secret_ref} resolved out of
   * band at load time, never inline (params ride Temporal history in plaintext
   * today; this is the split the review flagged).
   */
  params: Uint8Array;
  /** Dispatch knobs — the dispatcher's concern, not a workflow constant. */
  dispatch: DispatchOptions | undefined;
}

export interface Actor {
  name: string;
  /** immutable; bump on any input/output/params schema change */
  version: string;
}

export interface DispatchOptions {
  /** units per chunk (one chunk == one session) */
  chunk_size: number;
  /** max concurrent sessions */
  parallel_sessions: number;
  /** the Nexus operation deadline (caller-set; must */
  schedule_to_close_ms: number;
}
