// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: temporal/api/enums/v1/common.proto

/* eslint-disable */

export const protobufPackage = "temporal.api.enums.v1";

export enum EncodingType {
  ENCODING_TYPE_UNSPECIFIED = 0,
  ENCODING_TYPE_PROTO3 = 1,
  ENCODING_TYPE_JSON = 2,
  UNRECOGNIZED = -1,
}

export enum IndexedValueType {
  INDEXED_VALUE_TYPE_UNSPECIFIED = 0,
  INDEXED_VALUE_TYPE_TEXT = 1,
  INDEXED_VALUE_TYPE_KEYWORD = 2,
  INDEXED_VALUE_TYPE_INT = 3,
  INDEXED_VALUE_TYPE_DOUBLE = 4,
  INDEXED_VALUE_TYPE_BOOL = 5,
  INDEXED_VALUE_TYPE_DATETIME = 6,
  INDEXED_VALUE_TYPE_KEYWORD_LIST = 7,
  UNRECOGNIZED = -1,
}

export enum Severity {
  SEVERITY_UNSPECIFIED = 0,
  SEVERITY_HIGH = 1,
  SEVERITY_MEDIUM = 2,
  SEVERITY_LOW = 3,
  UNRECOGNIZED = -1,
}

/** State of a callback. */
export enum CallbackState {
  /** CALLBACK_STATE_UNSPECIFIED - Default value, unspecified state. */
  CALLBACK_STATE_UNSPECIFIED = 0,
  /** CALLBACK_STATE_STANDBY - Callback is standing by, waiting to be triggered. */
  CALLBACK_STATE_STANDBY = 1,
  /** CALLBACK_STATE_SCHEDULED - Callback is in the queue waiting to be executed or is currently executing. */
  CALLBACK_STATE_SCHEDULED = 2,
  /** CALLBACK_STATE_BACKING_OFF - Callback has failed with a retryable error and is backing off before the next attempt. */
  CALLBACK_STATE_BACKING_OFF = 3,
  /** CALLBACK_STATE_FAILED - Callback has failed. */
  CALLBACK_STATE_FAILED = 4,
  /** CALLBACK_STATE_SUCCEEDED - Callback has succeeded. */
  CALLBACK_STATE_SUCCEEDED = 5,
  /** CALLBACK_STATE_BLOCKED - Callback is blocked (eg: by circuit breaker). */
  CALLBACK_STATE_BLOCKED = 6,
  UNRECOGNIZED = -1,
}

/** State of a pending Nexus operation. */
export enum PendingNexusOperationState {
  /** PENDING_NEXUS_OPERATION_STATE_UNSPECIFIED - Default value, unspecified state. */
  PENDING_NEXUS_OPERATION_STATE_UNSPECIFIED = 0,
  /** PENDING_NEXUS_OPERATION_STATE_SCHEDULED - Operation is in the queue waiting to be executed or is currently executing. */
  PENDING_NEXUS_OPERATION_STATE_SCHEDULED = 1,
  /** PENDING_NEXUS_OPERATION_STATE_BACKING_OFF - Operation has failed with a retryable error and is backing off before the next attempt. */
  PENDING_NEXUS_OPERATION_STATE_BACKING_OFF = 2,
  /** PENDING_NEXUS_OPERATION_STATE_STARTED - Operation was started and will complete asynchronously. */
  PENDING_NEXUS_OPERATION_STATE_STARTED = 3,
  /** PENDING_NEXUS_OPERATION_STATE_BLOCKED - Operation is blocked (eg: by circuit breaker). */
  PENDING_NEXUS_OPERATION_STATE_BLOCKED = 4,
  UNRECOGNIZED = -1,
}

/** State of a Nexus operation cancellation. */
export enum NexusOperationCancellationState {
  /** NEXUS_OPERATION_CANCELLATION_STATE_UNSPECIFIED - Default value, unspecified state. */
  NEXUS_OPERATION_CANCELLATION_STATE_UNSPECIFIED = 0,
  /** NEXUS_OPERATION_CANCELLATION_STATE_SCHEDULED - Cancellation request is in the queue waiting to be executed or is currently executing. */
  NEXUS_OPERATION_CANCELLATION_STATE_SCHEDULED = 1,
  /** NEXUS_OPERATION_CANCELLATION_STATE_BACKING_OFF - Cancellation request has failed with a retryable error and is backing off before the next attempt. */
  NEXUS_OPERATION_CANCELLATION_STATE_BACKING_OFF = 2,
  /** NEXUS_OPERATION_CANCELLATION_STATE_SUCCEEDED - Cancellation request succeeded. */
  NEXUS_OPERATION_CANCELLATION_STATE_SUCCEEDED = 3,
  /** NEXUS_OPERATION_CANCELLATION_STATE_FAILED - Cancellation request failed with a non-retryable error. */
  NEXUS_OPERATION_CANCELLATION_STATE_FAILED = 4,
  /** NEXUS_OPERATION_CANCELLATION_STATE_TIMED_OUT - The associated operation timed out - exceeded the user supplied schedule-to-close timeout. */
  NEXUS_OPERATION_CANCELLATION_STATE_TIMED_OUT = 5,
  /** NEXUS_OPERATION_CANCELLATION_STATE_BLOCKED - Cancellation request is blocked (eg: by circuit breaker). */
  NEXUS_OPERATION_CANCELLATION_STATE_BLOCKED = 6,
  UNRECOGNIZED = -1,
}

export enum WorkflowRuleActionScope {
  /** WORKFLOW_RULE_ACTION_SCOPE_UNSPECIFIED - Default value, unspecified scope. */
  WORKFLOW_RULE_ACTION_SCOPE_UNSPECIFIED = 0,
  /** WORKFLOW_RULE_ACTION_SCOPE_WORKFLOW - The action will be applied to the entire workflow. */
  WORKFLOW_RULE_ACTION_SCOPE_WORKFLOW = 1,
  /** WORKFLOW_RULE_ACTION_SCOPE_ACTIVITY - The action will be applied to a specific activity. */
  WORKFLOW_RULE_ACTION_SCOPE_ACTIVITY = 2,
  UNRECOGNIZED = -1,
}

export enum ApplicationErrorCategory {
  APPLICATION_ERROR_CATEGORY_UNSPECIFIED = 0,
  /** APPLICATION_ERROR_CATEGORY_BENIGN - Expected application error with little/no severity. */
  APPLICATION_ERROR_CATEGORY_BENIGN = 1,
  UNRECOGNIZED = -1,
}

/**
 * (-- api-linter: core::0216::synonyms=disabled
 *     aip.dev/not-precedent: It seems we have both state and status, and status is a better fit for workers. --)
 */
export enum WorkerStatus {
  WORKER_STATUS_UNSPECIFIED = 0,
  WORKER_STATUS_RUNNING = 1,
  WORKER_STATUS_SHUTTING_DOWN = 2,
  WORKER_STATUS_SHUTDOWN = 3,
  UNRECOGNIZED = -1,
}
